 
 ############################## 
 # Country definition for ALB # 
 ############################## 
  

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag						= ALB 
	puppet					= ITA 
	manpower				= -20
	ai						= "alb_1936.ai"
	ai_settings				= { flags = { MOB1 = yes MOB2 = yes MOB3 = yes MOB4 = yes MOB5 = yes } }
	dissent					= 20
      
	# Resource Reserves 
	energy                 = 240
	metal                  = 120
	rare_materials         = 60
	oil                    = 500 
	supplies               = 500 
	money                  = 10 
      transports = 10
   capital                = 359 
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 3 
     political_left    = 4 
     free_market       = 7 
     freedom           = 5 
     professional_army = 5 
     defense_lobby     = 4 
     interventionism   = 1 
    } 
 
   nationalprovinces      = {  359 362 329 361 360 334  } 
   ownedprovinces         = {  359 360 361 362  } 
   controlledprovinces    = {  359 360 361 362  } 
   # Eastern Minor Tech '36 
   # Group D 1936 techs 
   # ###################### 
   # GW fighter 
   techapps               = {  
#Interwar Fighter  
4500 4510 4520 4530 4540 4550 4010
#Basic Armoured Car  
2860 2870 2880 2020
#Great War Heavy Field Artillery 
2290 2300 2310
#SW Tank 
7600 7610
#Great War Infantry Division  
1010  1020 1030 1040 1050 1060 
#Great War Cavalry Division  
13060 13070 13080 1310 1320 1330 1340
#Early Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240
 #Naval Infantry
#1560 
#Engineers
1830 1840 
# Inf support 
1910 1920 1930 1940 1950 1960
#Early Static Anti-Air Artillery 
2800 2450 21180 21190
#Basic Anti-Air Artillery Brigade 
2810 2820 2510
#Manufactoring
5810
#Basic Construction Engineering 
5800 5080 
#Medicine
5600
# Great War Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910
#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 
#Carrier Pigeons
30020 30030
} 
inventions = { 3000027 }
   diplomacy = 
   {  relation = {  tag = ITA value = 100 access = no  } 
    } 
   SpyInfo                = {  country = "ALB" NumberOfSpies = 3  } 
   headofstate            = {  type = 9 id = 285001  } 
   headofgovernment       = {  type = 9 id = 285002  } 
   foreignminister        = {  type = 9 id = 285003  } 
   armamentminister       = {  type = 9 id = 285004  } 
   ministerofsecurity     = {  type = 9 id = 285005  } 
   ministerofintelligence = {  type = 9 id = 285006  } 
   chiefofstaff           = {  type = 9 id = 285007  } 
   chiefofarmy            = {  type = 9 id = 285008  } 
   chiefofnavy            = {  type = 9 id = 285009  } 
   chiefofair             = {  type = 9 id = 285010  } 
  }
 