 #.#.# Abyssinia 
 
province = { id = 825   # Addis Abeba - North Ethiopia - Ethiopia
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 827   # Gode - Ethiopian Highland - Ethiopia
   landfort = 1 
 } 
 
province = { id = 828   # Harer - Ethiopian Highland - Ethiopia
   landfort = 1 
 } 
 
 #.#.# Albania 
 
province = { id = 359   # Tirana - Albania - Balkan
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 362   # Vlore - Albania - Balkan
   anti_air = 1 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 #.#.# Argentina 
 
province = { id = 2048   # La Plata - La Plata - Rio de la Plata
   anti_air = 2 
   naval_base = { size = 8 current_size = 8 } 
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 2050   # Buenos Aires - La Plata - Rio de la Plata
   anti_air = 3 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 2053   # Buenos Aires - La Plata - Rio de la Plata
   anti_air = 3 
   naval_base = { size = 3 current_size = 6 } 
 }  
 
 #.#.# Australia 
 
province = { id = 1234   # Buna
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1587   # Bougainville
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1602   # Lae
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1604   # Popondetta - Lae - New Guinea
   air_base = { size = 1 current_size = 1 } 
   anti_air = 1 
 } 
 
province = { id = 1605   # Wewak
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1607   # Port Moresby - Port Moresby - New Guinea
   naval_base = { size = 4 current_size = 4 } 
   air_base = { size = 2 current_size = 2 } 
   anti_air = 1 
 } 
 
province = { id = 1602   # Lae
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1694   # Collie - Perth - Australia
   anti_air = 5 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
   coastalfort = 1 
 } 
 
province = { id = 1697   # Darwin - Darwin - Australia
   anti_air = 5 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1704   # Brisbane - Brisbane - Australia
   anti_air = 4 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
 } 

province = { id = 1705   # Sydney - Sydney - Australia
   anti_air = 4 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1706   # Wollongong - Sydney - Australia
   anti_air = 3 
 } 
 
province = { id = 1707   # Canberra - Sydney - Australia
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1708   # Melbourne - Melbourne - Australia
   coastalfort = 2 
   anti_air = 3 
 } 
 
province = { id = 1712   # Adelaide - Adelaide - Australia
   anti_air = 1 
 } 
 
province = { id = 1713   # Robe - Adelaide - Australia
   anti_air = 2 
 } 
 
province = { id = 1724   # Manus
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1725   # Kavieng
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1726   # Rabaul - Rabaul - Bismarck Archipelago
   naval_base = { size = 7 current_size = 7 } 
   air_base = { size = 2 current_size = 2 } 
   anti_air = 2 
 } 
 
 #.#.# Austria 
 
province = { id = 189   # Innsbruck - Austria - Austria
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 191   # Klagenfurt - Austria - Austria
   anti_air = 1 
 } 
 
province = { id = 195   # Vienna - Austria - Austria
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
 } 
 
 #.#.# Belgium 
 
province = { id = 114   # Bruges - Flanders - Benelux
   naval_base = { size = 3 current_size = 3 } 
   anti_air = 1 
 } 
 
province = { id = 115   # Antwerpen - Flanders - Benelux
   air_base = { size = 3 current_size = 3 } 
   naval_base = { size = 10 current_size = 10 } 
   anti_air = 2 
 } 
 
province = { id = 116   # Brussels - Flanders - Benelux
   air_base = { size = 6 current_size = 6 } 
   anti_air = 1 
 } 
 
province = { id = 108   # Liege - Wallonia - Benelux
   landfort = 2 
   anti_air = 2 
 } 
 
province = { id = 894   # Matadi - Angolan Coast - Central Africa
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 #.#.# Bolivia 
 
province = { id = 2020   # Nuestra Senora de La Paz - La Paz - Andes
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
 #.#.# Brazil 
 
province = { id = 2057   # Curitiba - Sao Paulo - Brazilian Highlands
   anti_air = 1 
 } 
 
province = { id = 2058   # Porto Alegre - Sao Paulo - Brazilian Highlands
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 2059   # Sao Paulo - Sao Paulo - Brazilian Highlands
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 2067   # Goiania - Brasilia - Brazilian Highlands
   anti_air = 2 
 } 
 
province = { id = 2075   # Rio de Janeiro - Rio de Janeiro - Brazilian Highlands
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
 #.#.# British Raj 
 
province = { id = 1409   # Lashio - North Burma - Indochine
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1415   # Rangoon - Burma - Indochine
   anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1447   # Calcutta - Bengal - India
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1459   # Delhi - Delhi - India
   anti_air = 2 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1495   # Trivandrum - Western Ghat - India
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1517   # Bombay - Bombay - India
   anti_air = 3 
   air_base = { size = 7 current_size = 7 } 
   naval_base = { size = 7 current_size = 7 } 
 } 
 
province = { id = 1523   # Gwalior - Rajastan - India
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1533   # Karachi - Pakistan - India
   anti_air = 1 
   air_base = { size = 5 current_size = 5 } 
   naval_base = { size = 5 current_size = 5 } 
 } 
 
 #.#.# Bulgaria 
 
province = { id = 321   # Sofia - Bulgaria - Balkan
   anti_air = 2 
   air_base = { size = 2 current_size = 2 }
 } 
 
province = { id = 325   # Burgas - Bulgaria - Balkan
   anti_air = 2 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 5 current_size = 5 } 
 } 
 
 #.#.# Canada 
 
province = { id = 2089   # Vancouver - British Columbia - Western Canada
   anti_air = 3 
   air_base = { size = 8 current_size = 8 } 
   naval_base = { size = 10 current_size = 10 } 
 }
 
province = { id = 2090   # victoria - British Columbia - Western Canada
   anti_air = 1  
   naval_base = { size = 10 current_size = 10 }
   coastalfort = 2 
 }
 
province = { id = 2104   # Calgary - Alberta - Western Canada
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 2106   # Winnipeg - Manitoba - Canada
   anti_air = 1 
   air_base = { size = 5 current_size = 5 } 
 } 
 
province = { id = 2108   # Ottawa - Ontario - Canada
   anti_air = 3 
   air_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 2111   # Toronto - Ontario - Canada
   anti_air = 1 
 } 
 
province = { id = 2117   # Quebec - Quebec - Eastern Canada
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
   landfort = 6
   #coastalfort = 2
 }

province = { id = 2119   # Montreal - Quebec - Eastern Canada
   anti_air = 2 
 } 
 
province = { id = 2132   # Halifax - Nova Scotia - Eastern Canada
   anti_air = 1 
   air_base = { size = 5 current_size = 5 } 
   naval_base = { size = 10 current_size = 10 }
   coastalfort = 6 
 }
 
 #.#.# Chile 
 
province = { id = 2023   # Santiago de Chile - Chile - Andes
   anti_air = 2 
   naval_base = { size = 8 current_size = 8 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
 #.#.# China com 
 
province = { id = 1325 # Nanyang - Henan - China
	landfort = 2
}

province = { id = 1322 # Luoyang - Henan - China
	landfort = 2
}

province = { id = 1314 # Shiyan - Hubei - China
	landfort = 2
}
 
 #.#.# China Fengtian 
 
province = { id = 1247   # Beijing - Hebei - China
   air_base = { size = 5 current_size = 5 } 
 } 
 
 
 
province = { id = 1365   # Haikou - Guangdong - China
   anti_air = 2 
   air_base = { size = 6 current_size = 6 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1367   # Naoming - Guangdong - China
   naval_base = { size = 5 current_size = 5 } 
 } 
 
province = { id = 1369   # Guangzhou - Guangdong - China
   air_base = { size = 3 current_size = 3 } 
   naval_base = { size = 5 current_size = 5 } 
 } 
 
 #.#.# China National 
 
province = { id = 1297   # Chengdu - Sichuan - China
   air_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 1328   #  Quingdao - ? - China 
   naval_base = { size = 4 current_size = 4 } 
 } 

province = { id = 1330   # Jinan - Shandong - China
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1338   # Shanghai - Jiangsu - China
   naval_base = { size = 10 current_size = 10 } 
   landfort = 2
 } 
 
province = { id = 1345   # Hangzhou - Zhejiang - China
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1352   # Nanchang - Jiangxi - China
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1358   # Fuzhou - Fujian - China
   air_base = { size = 1 current_size = 1 } 
 } 

province = { id = 1312   # Hengyang - Hunan - China
   air_base = { size = 2 current_size = 2 } 
 } 
 #.#.# Columbia 

province = { id = 1338 # Shanghai - China
   landfort = 2 
}

province = { id = 1986   # Barranquilla - Panaman Ridge - Grand Colombia
   anti_air = 2 
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1991   # Santa Fe de Bogota - Maracaibo - Grand Colombia
   anti_air = 2 
 } 
 
 #.#.# Costa Rica 
 
province = { id = 2081   # San Jose - Nicaragua - Central America
   anti_air = 1 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 #.#.# Cuba 
 
province = { id = 1776   # Havana - Cuba - Caribbean
   anti_air = 1 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 #.#.# Czechoslovakia 
 
province = { id = 196   # Brno - Bohemia - Czechoslovakia
   anti_air = 2 
 } 
 
province = { id = 197   # Znojmo - Bohemia - Czechoslovakia
   landfort = 5 
 } 
 
province = { id = 200   # Liberec - Bohemia - Czechoslovakia
   landfort = 3 
 } 
 
province = { id = 203   # Tesin - Bohemia - Czechoslovakia
   landfort = 3 
 } 
 
province = { id = 204   # Prachatice - Bohemia - Czechoslovakia
   landfort = 4 
 } 
 
province = { id = 205   # Karlovy Vary - Bohemia - Czechoslovakia
   landfort = 4 
 } 
 
province = { id = 206   # Opava - Bohemia - Czechoslovakia
   landfort = 6 
 } 
 
province = { id = 207   # Prague - Bohemia - Czechoslovakia
   anti_air = 2 
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 208   # Bratislava - Slovakia - Czechoslovakia
   anti_air = 2 
   air_base = { size = 1 current_size = 1 } 
   landfort = 3 
 } 
 
province = { id = 209   # Kosice - Slovakia - Czechoslovakia
   landfort = 3 
 } 
 
province = { id = 210   # Komarno - Slovakia - Czechoslovakia
   landfort = 2 
 } 
 
province = { id = 215   # Uzhorod - Slovakia - Czechoslovakia
   landfort = 1 
 } 
 
province = { id = 470   # Granada - East Andalucia - Spain
   anti_air = 2 
   landfort = 2 
 } 
 
 #.#.# Denmark 
 
province = { id = 1   # Reykjavik - Iceland - Iceland
   anti_air = 1 
   naval_base = { size = 4 current_size = 4 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 218   # Frederikshavn - Denmark - Denmark
   anti_air = 1 
   naval_base = { size = 1 current_size = 1 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 294   # Copenhagen - Denmark - Denmark
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
 } 
 
 #.#.# Dominican Republic 
 
province = { id = 1780   # Ciudad Trujillo - Hispaniola - Caribbean
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 #.#.# Ecuador 
 
province = { id = 2040   # Santiago de Guayaquil - Quito - Andes
   naval_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 2042   # San Francisco de Quito - Quito - Andes
   anti_air = 2 
   air_base = { size = 1 current_size = 1 } 
 } 
 
 #.#.# Egypt 
 
province = { id = 787   # Cairo - Delta - Egypt
   anti_air = 2 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 789   # Alexandria - Delta - Egypt
   anti_air = 5 
   air_base = { size = 7 current_size = 7 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 
province = { id = 791   # Port Said - Suez Channel Area - Egypt
   anti_air = 2 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 #.#.# Estonia 
 
province = { id = 270   # Tallinn - Estonia - Baltic States
   anti_air = 2 
   naval_base = { size = 4 current_size = 4 } 
   air_base = { size = 2 current_size = 2 } 
 } 
 
 #.#.# Finland 
 
province = { id = 517   # Petsamo - Lapland - Finland
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 520   # Oulu - Central Finland - Finland
   air_base = { size = 2 current_size = 2 } 
   anti_air = 1 
 } 
 
province = { id = 524   # Turku - Oesterbotten - Finland
   coastalfort = 2 
   anti_air = 2 
   naval_base = { size = 6 current_size = 6 } 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 525   # Helsinki - South Finland - Finland
   coastalfort = 1 
   anti_air = 3 
   naval_base = { size = 4 current_size = 4 } 
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 526   # Ahvenanmaa - Oesterbotten - Finland
   coastalfort = 1 
 } 
 
province = { id = 527   # Tampere - South Finland - Finland
   anti_air = 2 
   air_base = 4 
 } 
 
province = { id = 528   # Mikkeli - South Finland - Finland
   anti_air = 2 
   air_base = 5 
 } 
 
province = { id = 529   # Kouvola - South Finland - Finland
   anti_air = 1 
 } 
 
province = { id = 531   # Viipuri - Karelia - Finland
   landfort = 8 
   anti_air = 4 
   air_base = 1 
   coastalfort = 2 
 } 
 
province = { id = 532   # Sortavala - Karelia - Finland
   anti_air = 6 
 } 
 
province = { id = 535   # Murmansk - Kola - White Sea Tundra
   air_base = 3 
 } 
 
#.#.# France 
 
province = { id = 37   # Brest - Brittany - France
   anti_air = 4 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 40   # Saint-Nazaire - Brittany - France
   anti_air = 2 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 43   # Cherbourg - Normandy - France
   anti_air = 3 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 44   # Caen - Normandy - France
   anti_air = 1 
 } 
 
province = { id = 51   # Dunkirk - Pas de Calais - France
   naval_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 52   # Lille - Pas de Calais - France
   anti_air = 1 
 } 
 
province = { id = 54   # Troyes - France
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 55   # Paris - Paris - France
   anti_air = 5 
   air_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 57   # Nantes - Loire - France
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 65   # Bourges - Loire - France
   air_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 68   # Bordeaux - Aquitaine - France
   air_base = { size = 5 current_size = 5 } 
 } 
 
province = { id = 69   # La Rochelle - Aquitaine - France
   anti_air = 4 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 72   # Chateauroux - Limousin_Auvergne - France
   anti_air = 1 
 } 
 
province = { id = 85   # Lyon - France
   air_base = { size = 3 current_size = 3 } 
 } 

province = { id = 86   # Toulon - Alpes_Provence - France
   anti_air = 3 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 87   # Nice - Alpes_Provence - France
   landfort = 5 
 } 
 
province = { id = 89   # Marseille - Alpes_Provence - France
   naval_base = { size = 5 current_size = 5 }
   anti_air = 2 
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 90   # Grenoble - Alpes_Provence - France
   landfort = 3 
 } 
 
province = { id = 91   # Chambery - Alpes_Provence - France
   landfort = 3 
 } 
 
province = { id = 96   # Longwy - Bourgogne_Champagne - France
   landfort = 2 
 } 

province = { id = 99   # Reims - France
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 104   # Metz - Lorraine_Alsace - France
   anti_air = 3 
   air_base = { size = 6 current_size = 6 } 
   landfort = 10 
 } 
 
province = { id = 105   # Colmar - Lorraine_Alsace - France
   anti_air = 2 
   landfort = 10 
 } 
 
province = { id = 107   # Strasbourg - Lorraine_Alsace - France
   anti_air = 2 
   landfort = 10 
 } 
 
province = { id = 717   # Rabat - Morocco - Morocco
   anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 727   # Algiers - Oran - Algeria
   anti_air = 2 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 728   # Oran - Oran - Algeria
 
   anti_air = 4 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 729   # Tlemcen - Oran - Algeria
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 747   # Tunis - Tunis - Tunisia
   anti_air = 4 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 748   # Bizerte - Tunis - Tunisia
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 833   # Djibouti - Somaliland - Horn of Africa
   anti_air = 1 
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 915   # Libreville - Cameroonian Jungle - Central Africa
   naval_base = { size = 3 current_size = 3 } 
 } 

province = { id = 907   # Brazzaville - Central Africa
   air_base = { size = 1 current_size = 1 } #for release of Free France
 } 

province = { id = 917   # Pointe-Noire - Cameroonian Jungle - Central Africa
   naval_base = { size = 1 current_size = 1 } #for release of Free France
}
 
province = { id = 962   # Abidjan - Ivory Coast - West Africa
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 978   # Dakar - Senegambia - West Africa
   anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1002   # Tamatave - Madagascar - Madagascar
   anti_air = 1 
   naval_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 1581   # Efate
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1582   # Espiritu Santo
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1586   # Nouvelle-Caledonie - South New Hebrides - South Solomon Islands
   anti_air = 1 
   naval_base = { size = 3 current_size = 3 } 
 } 

province = { id = 1743   # Papeete
   naval_base = { size = 1 current_size = 1 } 
 } 
 
 
 #.#.# Germany 
 
 
province = { id = 127   # Saarbrucken - Rhineland - Germany
   anti_air = 2 
   landfort = 1 
 } 
 
province = { id = 130   # Mainz - Rhineland - Germany
   landfort = 1 
 } 
 
 
 
province = { id = 132   # Freiburg - Baden_Wurttemberg - Germany
   landfort = 1 
 } 
 
province = { id = 134   # Stuttgart - Baden_Wurttemberg - Germany
 #   landfort = 1 
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 137   # Kassel - Hessen - Germany
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 138   # Frankfurt/Main - Hessen - Germany
   anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 145   # Essen - Westphalen - Germany
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 147   # Wilhelmshaven - Hannover_Magdeburg - Germany
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 10 current_size = 10 } 
 } 

province = { id = 148   # Bremen
   air_base = { size = 2 current_size = 2 }
   naval_base = { size = 5 current_size = 5 } 
}
 
province = { id = 151   # Lubeck - Holstein_Mecklemburg - Germany
   anti_air = 1 
 } 
 
province = { id = 152   # Kiel - Holstein_Mecklemburg - Germany
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 153   # Rostock - Holstein_Mecklemburg - Germany
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 154   # Hamburg - Holstein_Mecklemburg - Germany
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 155   # Stolp - Brandenburg - Germany
   landfort = 1 
 } 

province = { id = 158   # Stettin - Brandenburg - Germany
   landfort = 1 
 } 

province = { id = 161   # Deutsch-Krone - Brandenburg - Germany
   landfort = 1 
 } 

province = { id = 163   # Berlin - Brandenburg - Germany
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 167   # Breslau - Silesia - Germany
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 169   # Magdeburg - Sachsen - Germany
   anti_air = 2 
 } 
 
province = { id = 170   # Leipzig - Sachsen - Germany
   anti_air = 1 
 } 
 
province = { id = 177   # Nuremberg - Bavaria - Germany
   anti_air = 1 
 } 
 
province = { id = 179   # Munich - Bavaria - Germany
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 184   # Koenigsberg - East Prussia - Germany
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
   landfort = 4 
 } 
 
#.#.# Greece 
 
province = { id = 365   # Thessaloniki - Thrace - Balkan
   landfort = 5 
   anti_air = 2 
 } 
 
province = { id = 367   # Ioannina - Thrace - Balkan
   landfort = 5 
 } 
 
province = { id = 369   # Metsovo - Thrace - Balkan
   landfort = 5 
 } 
 
province = { id = 377   # Athens - Attica - Balkan
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 382   # Irakleio - Greek Island - Balkan
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
#.#.# Guatemala 
 
province = { id = 2088   # Ciudad de Guatemala - Central Rainforests - Central America
   anti_air = 1 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
#.#.# Haiti 
 
province = { id = 1781   # Port-au-Prince - Hispaniola - Caribbean
   anti_air = 1 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
#.#.# Holland 
 
province = { id = 118   # Eindhoven - Netherlands - Benelux
   anti_air = 2 
 } 
 
province = { id = 122   # Amsterdam - Netherlands - Benelux
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 125   # Rotterdam - Netherlands - Benelux
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
 } 

province = { id = 1596   # Hollandia
   naval_base = { size = 1 current_size = 1 } 
 } 
  
province = { id = 1638   # Bengkulu - Sumatra - Indonesia
   anti_air = 2 
   naval_base = { size = 7 current_size = 7 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1647   # Batavia - West Java - Indonesia
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1653   # Soerabaja - East Java - Indonesia
   anti_air = 2 
   naval_base = { size = 7 current_size = 7 } 
 } 
 
province = { id = 1659   # Manado - Celebes - Indonesia
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 2 current_size = 2 } 
 } 
 
 #.#.# Honduras 
 
province = { id = 2085   # Tegucigalpa - Nicaragua - Central America
   anti_air = 1 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 #.#.# Hungary 
 
province = { id = 284   # Budapest - Eastern Hungary - Hungary
   anti_air = 2 
   air_base = { size = 8 current_size = 8 } 
 } 
 
 #.#.# Iraq 
 
province = { id = 1032   # Basrah - Iraq - Middle East
   anti_air = 2 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1033   # El Hillah - Iraq - Middle East
   anti_air = 1 
 } 
 
province = { id = 1035   # Kut - Iraq - Middle East
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
 #.#.# Ireland 
 
province = { id = 34   # Dublin - Eire - Ireland
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
 #.#.# Italy 
 
province = { id = 378   # Kalymnos - Greek Island - Balkan
   air_base = { size = 4 current_size = 4 } 
   anti_air = 1 
   naval_base = { size = 6 current_size = 6 } 
   coastalfort = 4 
 } 
 
province = 
 { id = 379   # Rodos - Greek Island - Balkan
   anti_air = 1 
 } 
 
province = { id = 396   # Genoa - North Italy - Italy
   ic = { size = 4 current_size = 4 }
   landfort = 4 
   anti_air = 3 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 398   # Turin - North Italy - Italy
   ic = { size = 5 current_size = 5 }
   landfort = 4 
   anti_air = 1 
   air_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 400   # Venice - North Italy - Italy
   ic = { size = 4 current_size = 4 }
   coastalfort = 2 
   anti_air = 2 
   naval_base = { size = 6 current_size = 6 } 
   air_base = { size = 6 current_size = 6 } 
 } 

province = { id = 401   # Trento - North Italy - Italy
 ic = { size = 2 current_size = 2 }
 }
 
province = { id = 403   # Capodistria - North Italy - Italy
   landfort = 2 
 } 
 
province = 
 { id = 404   # Trieste - North Italy - Italy
   anti_air = 2 
 
   naval_base = { size = 4 current_size = 4 } 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 406   # Pola - North Italy - Italy
   anti_air = 1 
   landfort = 2 
   naval_base = { size = 6 current_size = 6 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 407   # Milan - North Italy - Italy
   air_base = { size = 10 current_size = 10 } 
   anti_air = 3 
 } 
 
province = { id = 408   # Parma - Appennine Ridge - Italy
   ic = { size = 3 current_size = 3 }
   anti_air = 1 
 } 
 
 
province = { id = 411   # Bologna - Appennine Ridge - Italy
   ic = { size = 4 current_size = 4 }
   anti_air = 1 
 } 
 
province = { id = 412   # Ancona - Appennine Ridge - Italy
   anti_air = 1 
   coastalfort = 1 
   naval_base = { size = 2 current_size = 2 } 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 419   # Rome - Central Italy - Italy
   ic = { size = 4 current_size = 4 }
   anti_air = 3 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 421   # Naples - South Italy - Italy
   ic = { size = 4 current_size = 4 }
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 422   # Taranto - South Italy - Italy
   ic = { size = 3 current_size = 3 }
   anti_air = 3 
   #coastalfort = 3 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
 } 
 
 
province = { id = 426   # Bari - South Italy - Italy
   air_base = { size = 4 current_size = 4 } 
   anti_air = 1 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 430   # Palermo - Sicilian Gap - Italy
   ic = { size = 1 current_size = 1 }
   anti_air = 2 
   #coastalfort = 1 
   naval_base = { size = 2 current_size = 2 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 433   # Siracuse - Sicilian Gap - Italy
   anti_air = 2 
  # coastalfort = 2 
   naval_base = { size = 4 current_size = 4 } 
   air_base = { size = 6 current_size = 6 } #was 4, increased for gameplay reasons 
 } 
 
province = { id = 434   # Cagliari - Ligurian Islands - Italy
   anti_air = 2 
   coastalfort = 1 
   naval_base = { size = 4 current_size = 4 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
 
province = { id = 435   # Sassari - Ligurian Islands - Italy
   anti_air = 1 
   naval_base = { size = 6 current_size = 6 } 
   air_base = { size = 4 current_size = 4 } 
} 
 
province = 
 { id = 750   # Tripoli - Tripoli - Libya
   anti_air = 1 
   naval_base = { size = 2 current_size = 2 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = 
 { id = 761   # Benghazi - Bengazi - Libya
   anti_air = 1 
   naval_base = { size = 2 current_size = 2 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = 
 { id = 765   # Tobruk - Tobruk - Libya
   anti_air = 2 
   naval_base = { size = 6 current_size = 6 } 
   air_base = { size = 4 current_size = 4 } 
   landfort = 3 
   coastalfort = 2 
 } 
 
province = 
 { id = 815   # Massawa - Red Sea Coast - Ethiopia
   anti_air = 1 
   naval_base = { size = 4 current_size = 4 } 
   air_base = { size = 4 current_size = 4 } 
 
 } 
province = 
 { id = 816   # Assab - Red Sea Coast - Ethiopia
   anti_air = 1 
   naval_base = { size = 4 current_size = 4 } 
   air_base = { size = 2 current_size = 2 } 
 
 } 
province = { id = 836   # Mogadishu - Somalia - Horn of Africa
   anti_air = 1 
   naval_base = { size = 2 current_size = 2 } 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 838   # Kismayo - Somalia - Horn of Africa
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
#.#.# Japan 
 
province = { id = 1219   # Port Arthur - Liaoning - China
   anti_air = 4 
   naval_base = { size = 5 current_size = 5 } 
   air_base = { size = 7 current_size = 7 } 
 } 
 
province = { id = 1226   # Ganggye - Pyongyang - Korea
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1228   # Seoul - Seoul - Korea
   anti_air = 3 
 } 
 
province = { id = 1232   # Busan - Seoul - Korea
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = 
 { id = 1362   # Taipei - Taiwan - China
   naval_base = { size = 4 current_size = 4 } 
   air_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 1550   # Yokohama - Tohoku - Japan
   anti_air = 2 
 } 
 
province = { id = 1551   # Niigata - Tohoku - Japan
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1552   # Tokyo - Tohoku - Japan
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1553   # Osaka - Honshu - Japan
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1554   # Hiroshima - Honshu - Japan
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1557   # Nagoya - Honshu - Japan
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1558   # Kyoto - Honshu - Japan
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1559   # Matsuyama - Kyushu_Shikoku - Japan
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1560   # Nagasaki - Kyushu_Shikoku - Japan
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1563   # Southern Okinawa - Ryukyusland - Japan
   anti_air = 2 
   air_base = { size = 6 current_size = 6 } 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 1661   # Iwo Jima - Bonin - Asian Pacific
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1662   # Chichi Jima - Bonin - Asian Pacific
   anti_air = 2 
 } 
 
 
province = { id = 1663   # Motoyama - Bonin - Asian Pacific
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1665   # Ponape - Carolinese - Asian Pacific
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1666   # Kusaie - Carolinese - Asian Pacific
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1667   # Truk - Carolinese - Asian Pacific
   anti_air = 5 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1668   # Woleai - Carolinese - Asian Pacific
   anti_air = 3 
   air_base = { size = 1 current_size = 1 }
 } 

province = { id = 1669   # Yap
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1670   # Peleliu
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 1 current_size = 1 } 
 } 
  
province = { id = 1672   # Minami Torishima
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 1 current_size = 1 } 
 } 

province = 
 { id = 1674   # Bikini - Marshalls - Asian Pacific
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = 
 { id = 1675   # Eniwetok - Marshalls - Asian Pacific
   anti_air = 5 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1676   # Kwajalein - Marshalls - Asian Pacific
   anti_air = 5 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1677   # Majuro
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1681   # Wotje
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1685   # Saipan
   anti_air = 5 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1686   # Pagan - North Marianes - Asian Pacific
   anti_air = 3 
 } 
 
#.#.# Latvia 
 
province = { id = 264   # Riga - Latvia - Baltic States
   anti_air = 1 
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 3 current_size = 3 } 
 } 
 
#.#.# Liberia 
 
province = { id = 969   # Monrovia - Guinean Coast - West Africa
   anti_air = 1 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 #Lithuania 
 
province = { id = 261   # Klaipeda - Lithuania - Baltic States
   anti_air = 1 
   naval_base = { size = 2 current_size = 2 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 262   # Kaunas - Lithuania - Baltic States
   air_base = { size = 2 current_size = 2 } 
 } 
 
 #.#.# Manchuko 
 
province = { id = 1199   # Harbin - Heilongjiang - China
   anti_air = 2 
   air_base = { size = 2 current_size = 2 } 
 } 
 
 #.#.# Syria 
 
province = { id = 1019   # Beirut - Lebanon_Syria - Middle East
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
#.#.# Mexico 
 
province = { id = 1973   # Leon de los Aldama - Mexico City - Mexico
   anti_air = 1 
 } 
 
province = { id = 1972   # Acapulco de Juarez - Mexico City - Mexico
   anti_air = 1 
 } 
 
province = { id = 1974   # Mexico City - Mexico City - Mexico
   anti_air = 2 
 } 
 
province = { id = 1970   # Oaxaca de Juarez - Vera Cruz - Mexico
   anti_air = 2 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
#.#.# Mongolia 
 
province = { id = 1124   # Ulaanbaatar - Mongolia - China
   air_base = { size = 1 current_size = 1 } 
 } 
 
 #.#.# NewZealand 
 
province = { id = 1721   # Wellington - New Zealand - Australia
   anti_air = 2 
   naval_base = { size = 5 current_size = 5 } 
   air_base = { size = 3 current_size = 3 } 
 } 

province = { id = 1731   # Apia
   naval_base = { size = 1 current_size = 1 } 
 } 
 
 
#.#.# Nicaragua 
 
province = { id = 2080   # Managua - Nicaragua - Central America
   naval_base = { size = 1 current_size = 1 } 
 } 
 
#.#.# Norway 
 
province = { id = 483   # Oslo - Southern Norway - Norway
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
   coastalfort = 3 
 } 
 
province = { id = 491   # Alesund - Southcentral Norway - Norway
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 5 current_size = 5 } 
   coastalfort = 3 
 } 
 
province = { id = 493   # Trondheim - Central Norway - Norway
   coastalfort = 2 
 } 
 
province = { id = 495   # Narvik - Central Norway - Norway
   anti_air = 1 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
#.#.# Oman 
 
province = { id = 1052   # Masqat - Yemenite Mountains - Middle East
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
#.#.# Panama 
 
province = { id = 2078   # Ciudad de Panama - Panaman Ridge - Central America
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
 } 
 
#.#.# Paraquay 
 
province = { id = 2047   # Nuestra Senora de la Asuncion - Asuncion - Gran Chaco
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
#.#.# Persia 
 
province = { id = 1091   # Gameroon - East Persia - Persia
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
#.#.# Peru 
 
province = { id = 2016   # Lima - Lima - Andes
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
#.#.# Philipines 
 
province = { id = 1565   # Manila - Luzon - Philippines
   anti_air = 2 
   naval_base = { size = 8 current_size = 8 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1566   # Cabanatuan - Luzon - Philippines
   anti_air = 4 
   air_base = { size = 5 current_size = 5 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 #.#.# Poland 
 
province = { id = 222   # Torun - Poznan - Poland
   anti_air = 2 
 } 
 
province = 
 { id = 224   # Poznan - Poznan - Poland
   anti_air = 4 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 225   # Bydgoszcz - Poznan - Poland
   anti_air = 1 
 } 
 
province = { id = 226   # Gdynia - Poznan - Poland
   anti_air = 2 
   naval_base = { size = 8 current_size = 8 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 227   # Czestochowa - Poznan - Poland
   air_base = { size = 3 current_size = 3 } 
   anti_air = 3 
 } 
 
province = { id = 228   # Siedlce - Warsaw - Poland
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 230   # Plock - Warsaw - Poland
   anti_air = 1 
 } 
 
province = { id = 232   # Warsaw - Warsaw - Poland
   anti_air = 2 
   air_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 235   # Krakow - Krakow - Poland
   anti_air = 2 
 } 
 
province = { id = 240   # Tarnopol - Lvov - Poland
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 252   # Suwalki - Polotsk - Poland
   anti_air = 1 
 } 
 
#.#.# Portugal 
 
province = { id = 476   # Lisbon - Portugal - Portugal
   anti_air = 4 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 481   # Porto - Portugal - Portugal
   anti_air = 1 
 } 
 
province = { id = 856   # Maxixe - Mocambique - East Africa
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 892   # Lobito - Angolan Coast - Central Africa
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 893   # Cabinda - Angolan Coast - Central Africa
   naval_base = { size = 1 current_size = 1 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 912   # Sao Tome - Cameroonian Jungle - Central Africa
   anti_air = 2 
   naval_base = { size = 1 current_size = 1 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 963   # Bissau - Guinean Coast - West Africa
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 992   # Cape Verde - Cap Verde Islands - West Africa
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 995   # The Azores - The Azores - Portugal
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1372   # Macao - Guangdong - China
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1617   # Dili - Flores_Timor - Indonesia
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
#.#.# Romania 
 
province = { id = 306   # Ismail - Bessarabia - Romania
   anti_air = 1 
 } 
 
province = { id = 310   # Constantza - South Romania - Romania
   naval_base = { size = 4 current_size = 4 }
   air_base = { size = 1 current_size = 1 }
   anti_air = 2 
 }
 
province = { id = 311   # Ploesti - South Romania - Romania
   anti_air = 3 
 } 
 
province = { id = 316   # Bucharest - South Romania - Romania
   anti_air = 2 
   air_base = { size = 5 current_size = 5 } 
 } 
 
#.#.# San Salvador 
 
province = { id = 2079   # San Salvador - Nicaragua - Central America
   naval_base = { size = 1 current_size = 1 } 
 } 
 
 #.#.# Saudi Arabia 
 
province = { id = 1048   # Medina - Hedjaz - Middle East
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
#.#.# Siam 
 
province = { id = 1424   # Nakhon Sawan - Siam - Indochine
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
#.#.# South Africa 
 
province = { id = 872   # Pretoria - Transvaal_Natal - South Africa
   anti_air = 3 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 876   # Johannesburg - Transvaal_Natal - South Africa
   anti_air = 3 
 } 
 
province = { id = 880   # Cape Town - Cape - South Africa
   anti_air = 4 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 881   # Port Elizabeth - Cape - South Africa
   anti_air = 1 
 } 
 
province = { id = 882   # Swakopmund - Nambia - Southwest Africa
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
#.#.# Soviet Union 
 
province = { id = 535   # Murmansk - Kola - White Sea Tundra
   anti_air = 4 
   naval_base = { size = 7 current_size = 7 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 542   # Arkhangelsk - Arkhangelsk - Northern Russia
   anti_air = 4 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 550   # Kingisepp - Novgorod - Western Russia
   landfort = 1 
} 
 
province = { id = 552   # Gdov - Novgorod - Western Russia
   landfort = 1 
 } 
 
province = { id = 553   # Leningrad - Leningrad - Russia
   anti_air = 6 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
   landfort = 5 
   coastalfort = 5 
 } 
 
province = { id = 561   # Staraya Russa - Pskov - Western Russia
   anti_air = 1 
 } 
 
province = { id = 563   # Torzhok - Velikiye Luki - Russia
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 564   # Opochka - Pskov - Western Russia
   landfort = 1 
 } 
 
province = { id = 566   # Pskov - Pskov - Western Russia
   air_base = { size = 6 current_size = 6 } 
   landfort = 1 
 } 
 
province = { id = 572   # Moscow - Moscow - Russia
   air_base = { size = 10 current_size = 10 } 
   landfort = 5 
   anti_air = 4 
 } 
 
province = { id = 585   # Kozelsk - Ryazan - Russia
   air_base = { size = 3 current_size = 3 } 
   anti_air = 1 
 } 
 
province = { id = 587   # Klintsy - Smolensk - Western Russia
   anti_air = 2 
 } 
 
province = { id = 589   # Smolensk - Smolensk - Western Russia
   anti_air = 3 
 } 
 
province = { id = 590   # Vitebsk - Minsk - Belarus
   air_base = { size = 2 current_size = 2 } 
   anti_air = 2 
 } 
 
province = { id = 592   # Borisov - Minsk - Belarus
   landfort = 2 
} 
 
province = { id = 593   # Polotsk - Minsk - Belarus
   landfort = 1 
 } 
 
province = { id = 595   # Mozyr - Mozyr - Belarus
   landfort = 2 
 } 
 
province = { id = 596   # Slutsk - Rogachev - Belarus
   landfort = 2 
 } 
province = { id = 597   # Luban - Mozyr - Belarus
   air_base = { size = 2 current_size = 2 } 
   landfort = 2 
 } 
 
province = { id = 599   # Minsk - Minsk - Belarus
   landfort = 2 
 } 
 
province = { id = 600   # Mogilev - Rogachev - Belarus
   air_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 604   # Kursk - Kursk - Southern Russia
   air_base = { size = 5 current_size = 5 } 
 } 
 
province = { id = 614   # Proskurov - Transnistria - Ukraine
   landfort = 2 
 } 
 
province = { id = 616   # Novograd-Volynsky - Transnistria - Ukraine
   landfort = 2 
} 
 
province = { id = 617   # Kiev - Kiev - Ukraine
   air_base = { size = 8 current_size = 8 } 
   anti_air = 3 
 } 
 
province = { id = 618   # Kamenets-Podolsky - Transnistria - Ukraine
   landfort = 1 
 } 
 
province = { id = 626   # Odessa - Odessa - Ukraine
   air_base = { size = 4 current_size = 4 } 
   anti_air = 3 
 } 
 
province = { id = 629   # Poltava - Poltava - Ukraine
   anti_air = 2 
 } 
 
province = { id = 631   # Mariupol - Dnepropretovsk - Ukraine
   air_base = { size = 4 current_size = 4 } 
   anti_air = 2 
 } 
 
province = { id = 636   # Kharkov - Kharkov - Ukraine
   air_base = { size = 2 current_size = 2 } 
   anti_air = 1 
 } 
 
province = { id = 639   # Dzhankoy - Krim - Ukraine
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 641   # Sevastopol - Krim - Ukraine
   anti_air = 6 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 6 current_size = 6 } 
   landfort = 3 
   coastalfort = 5 
 } 
 
province = { id = 648   # Rossosh - Belgorod - Southern Russia
   anti_air = 1 
 } 
 
province = { id = 653   # Pavlovsk - Tambov - Southern Russia
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 663   # Stalingrad - Stalingrad - Southern Russia
   air_base = { size = 4 current_size = 4 } 
   landfort = 5 
   anti_air = 3 
 } 
 
province = { id = 666   # Engels - Engels - Eastern Russia
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 669   # Saratov - Penza - Southern Russia
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 706   # Astrakhan - Astrakhan - Kaukasus
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 708   # Kutaisi - Georgien - Kaukasus
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1130   # Berezniki - Perm - Urals
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1134   # Orenburg - Orenburg - Eastern Russia
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1138   # Omsk - Omsk - Novosibirsk
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1143   # Biysk - Novosibirsk - Novosibirsk
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1164   # Ust-Kut - Irkutsk - Irkutsk
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 1176   # Blagoveshchensk - Amur - Far East Siberia
   anti_air = 2 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1185   # Sovetskaya Gavan - Khabarovsk - Far East Siberia
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1191   # Vladivostok - Primorski - Far East Siberia
   anti_air = 5 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
   landfort = 1 
   coastalfort = 3 
 } 
 
province = { id = 1194   # Lesozavodsk - Primorski - Far East Siberia
   anti_air = 2 
 } 


province = { id = 654 # Voronezh
   air_base = { size = 2 current_size = 1 }
 }
province = { id = 588 # Bryansk
   air_base = { size = 4 current_size = 3 }
 }
province = { id = 589 # Smolensk
   air_base = { size = 2 current_size = 2 }
 }
 province = { id = 611 # Zhitomir
   air_base = { size = 1 current_size = 1 }
 }
 province = { id = 628 # Kirovograd
   air_base = { size = 2 current_size = 2 }
 }
 province = { id = 630 # Zaporozhye
   air_base = { size = 2 current_size = 2 }
 }
 province = { id = 1169 # Chita
   air_base = { size = 2 current_size = 2 }
 }
 province = { id = 1190 # Khabarovsk
   air_base = { size = 4 current_size = 3 }
 }
 province = { id = 644 # Rostov na Donu
   air_base = { size = 2 current_size = 2 }
 } 
 
#.#.# Spain 
 
province = { id = 436   # Tarragona - Catalonia - Spain
   anti_air = 2 
   naval_base = { size = 7 current_size = 7 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 441   # Coruna - Cantabric Chain - Spain
   anti_air = 2 
   naval_base = { size = 7 current_size = 7 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 460   # Madrid - Central Spain - Spain
   anti_air = 3 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 464   # Valencia - Levant - Spain
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 473   # Cadiz - West Andalucia - Spain
   naval_base = { size = 5 current_size = 7 } 
 } 
 
province = { id = 474   # Sevilla - West Andalucia - Spain
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 475   # Palma de Mallorca - Baleares - Spain
   anti_air = 2 
   naval_base = { size = 7 current_size = 7 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 988   # Villa Cisneros - Rio de Oro - Sahara
   anti_air = 2 
   naval_base = { size = 2 current_size = 2 } 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 990   # Las Palmas de Gran Canaria - Canarias - Sahara
   naval_base = { size = 1 current_size = 1 } 
   air_base = { size = 2 current_size = 2 } 
 } 
 
#.#.# Sweden 
 
province = { id = 2153   # Gothenburg - Goetaland - Sweden
   naval_base = { size = 5 current_size = 5 } 
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 2159   # Stockholm - Oestra Svealand - Sweden
   anti_air = 5 
   naval_base = { size = 5 current_size = 5 } 
   air_base = { size = 3 current_size = 3 } 
 } 
 
#.#.# Switzerland 
 
province = { id = 389   # Zurich - Switzerland - Switzerland
   landfort = 5 
   anti_air = 3 
} 
 
province = { id = 390   # Lugano - Switzerland - Switzerland
   landfort = 4 
   anti_air = 3 
 } 
 
province = { id = 391   # Geneva - Switzerland - Switzerland
   landfort = 5 
   anti_air = 3 
} 
 
province ={ id = 392   # Bern - Switzerland - Switzerland
   anti_air = 5 
   air_base = { size = 4 current_size = 4 } 
   landfort = 5 
 } 
 
#.#.# Turkey 
 
province = { id = 1075   # Ankara - Central Turkey - Anatolia
   anti_air = 4 
   air_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 1076   # Izmit - Bosporus - Anatolia
   anti_air = 4 
   air_base = { size = 6 current_size = 6 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 1054   # ANTAYA - Bosporus - Anatolia
   naval_base = { size = 4 current_size = 4 } 
 } 
 
#.#.# United Kingdom 
 
province = { id = 5   # Scapa Flow - North Scotland - Scotland
   anti_air = 4 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 10   # Dumfries - South Scotland - Scotland
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 17   # Manchester - North England - England
   naval_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 18   # Sheffield - North England - England
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 19   # Bristol - West England - England  anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 20   # Exeter - West England - England
   anti_air = 6 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 23   # Plymouth - West England - England
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 1 
 } 
 
province = { id = 25   # Norwich - East England - England
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 26   # Dover - East England - England
   anti_air = 5 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 3 
 } 
 
province = { id = 27   # Portsmouth - East England - England
   anti_air = 6 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
province = { id = 28   # Oxford - East England - England
   anti_air = 2 
 } 

province = { id = 11   # Glasgow - South Scotland - Scotland
   naval_base = { size = 5 current_size = 5 }
 }
province = { id = 12   # Edinburgh - South Scotland - Scotland
   naval_base = { size = 4 current_size = 4 }
 }

province = { id = 36   # Belfast - Northern Ireland
   naval_base = { size = 5 current_size = 5 }
 }
 
province = { id = 348   # Gibraltar - West Andalucia - Spain
   anti_air = 6 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 10 current_size = 10 } 
   landfort = 6 
 } 
 
province = { id = 388   # Nicosia - Anatolian South Coast - Anatolia
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 429   # Malta - Sicilian Gap - Italy
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 5 current_size = 5 } 
   coastalfort = 1 
 } 
 
province = { id = 810   # Khartoum - Upper Nile Valley - Sudan
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 842   # Mombasa - Kenya - East Africa
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 900   # Suez - Suez Channel Area - Egypt
   anti_air = 2 
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 929   # Lagos - South Nigeria - West Africa
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 956   # Accra - Gold Coast - West Africa
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 964   # Freetown - Guinean Coast - West Africa
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1008   # Tel Aviv - Palestine - Middle East
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 2 current_size = 2 } 
   province_revoltrisk = 5 } 
 
province = { id = 1009   # Gaza - Palestine - Middle East
   province_revoltrisk = 5 } 
province = { id = 1010   # Eilat - Palestine - Middle East
   province_revoltrisk = 5 } 
province = { id = 1011   # Haifa - Palestine - Middle East
   province_revoltrisk = 5 } 
province = { id = 1172   # Jerusalem - Palestine - Middle East
   anti_air = 1 
   province_revoltrisk = 5 } 
province = { id = 1013   # Akko - Palestine - Middle East
   province_revoltrisk = 5 } 
province = { id = 1022   # Amman - Transjordan - Middle East
   province_revoltrisk = 2 } 
province = { id = 1023   # Irbid - Transjordan - Middle East
   province_revoltrisk = 2 } 
province = { id = 1024   # Az Zarqa - Transjordan - Middle East
   province_revoltrisk = 2 } 
province = { id = 1025   # Ma'an - Transjordan - Middle East
   province_revoltrisk = 2 } 
province = { id = 1026   # Al Kerak - Transjordan - Middle East
   province_revoltrisk = 2 } 
 
province = { id = 1053   # Aden - Yemenite Mountains - Middle East
   anti_air = 1 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1371   # Hong Kong - Guangdong - China
   anti_air = 4 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 1 
 } 
 
province = { id = 1432   # Singapore - Malacka - Indochine
   anti_air = 6 
   air_base = { size = 8 current_size = 8 } 
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 3 
 } 
 
province = { id = 1510   # Kandy - Ceylon - India
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1511   # Colombo - Ceylon - India
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 3 
 } 
 
province = { id = 1589   # New Georgia
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1590   # Lunga
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1611   # Male - Diego Garcia Island - Diego Garcia Island
   anti_air = 2 
   air_base = { size = 6 current_size = 6 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1624   # Kuching - North Borneo - Indonesia
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1678   # Makin
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1680   # Tarawa
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1682   # Nauru
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1728   # Suva
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1771   # The Bahamas - Bahamas Islands - Caribbean
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1773   # The Bermudas - Bermuda - Caribbean
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1997   # Georgetown - Guayana - Grand Colombia
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 2045   # Falkland Islands - The Falklands - Patagonia
   anti_air = 2 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 5 current_size = 5 } 
 } 
 
province = { id = 2137   # St. John's - New Foundland - Eastern Canada
   anti_air = 2 
   air_base = { size = 6 current_size = 6 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
#.#.# Urugay 
 
province = { id = 2052   # Montevideo - La Plata - Rio de la Plata
   anti_air = 1 
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
#.#.# Usa 
 
province = { id = 889   # Balboa - Panaman Ridge - Central America
   anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1673   # Wake - Marcus_Wake - Asian Pacific
   anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1683   # Guam - North Marianes - Asian Pacific
   anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1733   # Pago Pago
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1734   # Pearl Harbor - Hawaii - American Pacific
   anti_air = 3 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1735   # Kauai
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1736   # Hawaii
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1737   # Maui
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1738   # Johnston
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1739   # Midway
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1747   # Palmyra
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1751   # Baker Island
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1778   # Guantanamo Bay Naval Base - Cuba - Caribbean
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 1787   # Concord - New Hampshire - Northeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1789   # Boston - Massachussets - Northeast US
   anti_air = 3 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1792   # Syracuse - New York - Northeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1795   # New York - New York - Northeast US
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1796   # Providence - Pennsylvania - Northeast US
   naval_base = { size = 8 current_size = 8 } 
  }
 
province = { id = 1805   # Philadelphia - Pennsylvania - Northeast US
   naval_base = { size = 8 current_size = 8 } 
   anti_air = 2 
 } 
 
province = { id = 1806   # Pittsburgh - Pennsylvania - Northeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1808   #  Baltimore - Maryland_Delaware - Northeast US
    naval_base = { size = 6 current_size = 6 } 
} 

province = { id = 1809   # Washington - Maryland_Delaware - Northeast US
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1812   # Norfolk - Virginia - Northeast US
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1820   # Lexington - Kentucky - Northeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1832   # Chicago - Illinois - Midwest US
   anti_air = 3 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1833   # Saint Louis - Missouri - Midwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1839   # Milwaukee - Wisconsin - Midwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1845   # Detroit - Michigan - Midwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1846   # Rochester - Minnesota - Midwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1855   # Fargo - North Dakota - Midwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1859   # Lincoln - Nebraska - Midwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1874   # Seattle - Washington - Northwest US
   anti_air = 1 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1878   # Portland - Oregon - Northwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1886   # San Diego - California - Southwest US
   anti_air = 1 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1887   # Los Angeles - California - Southwest US
   anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 1888   # Sacramento - California - Southwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1889   # San Francisco - California - Southwest US
   anti_air = 3 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1896   # Salt Lake City - Utah - Southwest US
   anti_air = 1 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1901   # Tucson - Arizona - Southwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1906   # Santa Fe - New Mexico - Southcentral US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1908   # Denver - Colorado - Southcentral US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1913   # Oklahoma City - Oklahoma - Southcentral US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1922   # Corpus Christi - Texas - Southcentral US
   anti_air = 1 
   air_base = { size = 6 current_size = 6 } 
   naval_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 1928   # Houston - Texas - Southcentral US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1940   # Memphis - Tennessee - Southeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1944   # Mobile - Alabama - Southeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1952   # Jacksonville - Florida - Southeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1953   # Miami - Florida - Southeast US
   anti_air = 1 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1955   # Atlanta - Georgia - Southeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1960   # Charleston - South Carolina - Southeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1962   # Charlotte - North Carolina - Southeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
 
province = { id = 2142   # Anchorage - Alaska - Alaska
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 2174   # Attu Island - Alaskan Archipelago - Alaska
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 1 current_size = 1 } 
 } 
 
#.#.# Venezuela 
 
province = { id = 1988   # Maracaibo - Maracaibo - Grand Colombia
   anti_air = 2 
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 1993   # Caracas - Caracas - Grand Colombia
   anti_air = 2 
 } 
 
#.#.# Yugoslavia 
 
province = { id = 332   # Cetinje - East Serbia - Balkan
   naval_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 338   # Belgrade - Central Serbia - Balkan
   anti_air = 3 
   air_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 343   # Dubrovnik - Croatia - Balkan
   anti_air = 2 
 } 
 
province = { id = 350   # Split - Croatia - Balkan
   anti_air = 2 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 352   # Zagreb - Croatia - Balkan
   anti_air = 2 
 } 


# Indochinese Union
province =  { id = 1395 # Hanoi - Vietnam
   anti_air   = 4 
   air_base   = {  size =  4 current_size =  4  } 
   naval_base = {  size =  4 current_size =  4  } 
 }    
  
province = { id = 1399 # Saigon - Vietnam
   anti_air   = 3 
   air_base   = {  size =  4 current_size =  4  } 
   naval_base = {  size =  4 current_size =  4  } 
 }       
  
