
## Day of Decision

### USA -25 IC

province = { id = 1940   # Memphis - Tennessee
   ic = -1
   #infrastructure = -20
 } 
#province = { id = 1943   # Tennessee
#   infrastructure = -20
# } 
#province = { id = 1955   # Tennessee
#   infrastructure = -20
# } 

province = { id = 1795 ic = -3 } 
province = { id = 1805 ic = -2 } 
province = { id = 1833 ic = -2 } 
province = { id = 1896 ic = -2 } 
province = { id = 1825 ic = -2 } 
province = { id = 1908 ic = -2 } 
province = { id = 1832 ic = -2 } 
province = { id = 1845 ic = -2 } 
province = { id = 1789 ic = -2 } 
province = { id = 1886 ic = -2 } 
province = { id = 1839 ic = -2 } 
province = { id = 1931 ic = -1 } 

### UK -10 IC

province = { id = 17 ic = -3 } 
province = { id = 18 ic = -2 } 
province = { id = 22 ic = -2 } 
province = { id = 24 ic = -1 } 
province = { id = 29 ic = -3 } 

### France -15 IC

province = { id = 55 ic = -2 } 
province = { id = 45 ic = -1 } 
province = { id = 52 ic = -2 } 
province = { id = 64 ic = -1 } 
province = { id = 77 ic = -2 } 
province = { id = 78 ic = -1 } 
province = { id = 85 ic = -1 } 
province = { id = 89 ic = -1 } 
province = { id = 48 ic = -1 } 
province = { id = 53 ic = -1 } 
province = { id = 59 ic = -1 } 
province = { id = 58 ic = -1 } 
province = { id = 80 ic = -1 } 
province = { id = 104 landfort = -3 } 
province = { id = 105 landfort = -3 } 
province = { id = 107 landfort = -3 } 

# Morocco

province = { id = 720 province_revoltrisk = 5 } 
province = { id = 722 province_revoltrisk = 5 } 
province = { id = 725 province_revoltrisk = 5 } 
province = { id = 719 province_revoltrisk = 5 } 
province = { id = 718 province_revoltrisk = 2 } 
province = { id = 717 province_revoltrisk = 2 } 
province = { id = 721 province_revoltrisk = 2 } 
province = { id = 723 province_revoltrisk = 2 } 

### Germany -15 IC

province = { id = 134 ic = -2 }
province = { id = 136 ic = -1 }  
province = { id = 138 ic = -2 } 
province = { id = 142 ic = -2 } 
province = { id = 145 ic = -2 } 
province = { id = 146 ic = -1 } 
province = { id = 154 ic = -1 } 
province = { id = 166 ic = -1 } 
province = { id = 170 ic = -1 } 
province = { id = 173 ic = -1 } 
province = { id = 184 ic = -1 } 

### USSR -50 IC

 province = { id = 536   #  Kandalaksha - Kola - White Sea Tundra
   ic = -1 }  
 province = { id = 663   #  Stalingrad - Stalingrad - Southern Russia
   ic = -1 
 } 
 province = { id = 668   #  Kuybyshev - Kuybyshev - Russia
   ic = -2 } 
 province = { id = 669   #  Saratov - Penza - Southern Russia
   ic = -2 } 
 province = { id = 672   #  Kazan - Kazan - Northern Russia
   ic = -2 } 
 province = { id = 680   #  Gorky - Nizhnij Novgorod - Northern Russia
   ic = -1 } 
 province = { id = 684   #  Kirov - Kazan - Northern Russia
   ic = -1 } 
 province = { id = 687   #  Perm - Perm - Urals
   ic = -5 } 
 province = { id = 688   #  Ukhta - Kirov - Northern Russia
   ic = -1 } 
 province = { id = 690   #  Sterlitamak - Orenburg - Eastern Russia
   ic = -1 } 
 province = { id = 706   #  Astrakhan - Astrakhan - Kaukasus
  ic = -2 }  
 province = { id = 709   #  Tbilisi - Georgien - Kaukasus
   ic = -1 } 
 province = { id = 711   #  Yerevan - Armenia_Azerbaijan - Kaukasus
   ic = -1 } 
 province = { id = 713   #  Baku - Armenia_Azerbaijan - Kaukasus
   ic = -1 } 
 province = { id = 1097   #  Ashkhabad - Turkmenistan - Central Asia
  ic = -1 } 
 province = { id = 1098   #  Merv - Turkmenistan - Central Asia
   ic = -1 } 
 province = { id = 1099   #  Samarkand - Uzbekistan - Central Asia
   ic = -1 } 
 province = { id = 1100   #  Bukhara - Uzbekistan - Central Asia
   ic = -1 } 
 province = { id = 1113   #  Uralsk - Kirgiz Steppe - Kazakstan
   ic = -1 } 
 province = { id = 1118   #  Shevchenko - Kirgiz Steppe - Kazakstan
   ic = -1 } 
 province = { id = 1119   #  Kyzyl - Mongolia - Krasnoyarsk
   ic = -4 } 
 province = { id = 1128   #  Nizhny Tagil - Sverdlovsk - Urals
   ic = -1 } 
 province = { id = 1129   #  Vorkuta - Vorkuta - Urals
   ic = -1 } 
province = { id = 1130   #  Berezniki - Perm - Urals
  ic = -1 } 
 province = { id = 1131   #  Ufa - Ufa - Eastern Russia
   ic = -1 } 
 province = { id = 1132   #  Chelyabinsk - Ufa - Eastern Russia
   ic = -1 } 
 province = { id = 1134   #  Orenburg - Orenburg - Eastern Russia
   ic = -1 } 
 province = { id = 1137   #  Kurgan - Tyumen - Novosibirsk
   ic = -1 } 
 province = { id = 1138   #  Omsk - Omsk - Novosibirsk
   ic = -1 } 
 province = { id = 1140   #  Barnaul - Novosibirsk - Novosibirsk
   ic = -1 } 
 province = { id = 1142   #  Novosibirsk - Novosibirsk - Novosibirsk
   ic = -1 } 
province = { id = 1144   #  Kemerovo - Novosibirsk - Novosibirsk
   ic = -1 } 
 province = { id = 1145   #  Stalinsk - Novosibirsk - Novosibirsk
   ic = -1 } 
 province = { id = 1148   #  Tomsk - Tomsk - Tomsk
   ic = -1 } 
 province = { id = 1151   #  Sverdlovsk - Sverdlovsk - Urals
   ic = -2 } 
 province = { id = 1156   #  Krasnoyarsk - North Krasnoyarsk - Krasnoyarsk
   ic = -1 } 
 province = { id = 1162   #  Irkutsk - Irkutsk - Irkutsk
   ic = -1 } 
 province = { id = 1170   #  Never - Amur - Far East Siberia
   ic = -1 } 

 # Stalin Line

 province = { id = 550 landfort = -1 } 
 province = { id = 566 landfort = -1 } 
 province = { id = 564 landfort = -1 } 
 province = { id = 593 landfort = -1 } 
 province = { id = 618 landfort = -1 } 
 province = { id = 592 landfort = -2 } 
 province = { id = 599 landfort = -2 } 
 province = { id = 596 landfort = -2 } 
 province = { id = 597 landfort = -2 } 
 province = { id = 595 landfort = -2 } 
 province = { id = 616 landfort = -2 } 
 province = { id = 614 landfort = -2 } 
 
### Japan -15 IC #Reduced to -5 in DH 1.04

province = { id = 1545 ic = -1 } 
province = { id = 1546 ic = -1 } 
province = { id = 1547 ic = -1 } 
province = { id = 1549 ic = -1 } 
province = { id = 1551 ic = -1 } 
#province = { id = 1552 ic = -3 } 
#province = { id = 1553 ic = -2 } 
#province = { id = 1554 ic = -2 } 
#province = { id = 1555 ic = -1 } 
#province = { id = 1559 ic = -1 } 
#province = { id = 1560 ic = -1 } 

#### Italy -5 IC

province = { id = 396 ic = -1 } 
province = { id = 398 ic = -1 } 
#province = { id = 400 ic = -1 } 
province = { id = 407 ic = -1 } 
province = { id = 421 ic = -1 } 

#### China -4 IC
#province = { id = 1299 ic = -1 } #Chongqing 
#province = { id = 1308 ic = -1 } #Changsha
#province = { id = 1317 ic = -1 } #Wuhan
#province = { id = 1337 ic = -1 } #Nanjing

### Czechoslovakia
province = { id = 197 landfort = -4 } #Znojmo