 
 ############################## 
 # Country definition for the British Raj # 
 ############################## 

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = U02  
	ai = "u02_1936.ai"
	ai_settings	= { flags = { MOB1 = yes MOB2 = yes } }
	dissent = 20
	regular_id             = IND 
	puppet                 = ENG 
	capital                = 1459 
	manpower               = 493    

	relative_manpower = 0.6000 
	# Resource Reserves 
	energy                 = 5520
	metal                  = 2760
	rare_materials         = 1380
	oil                    = 500 
	supplies               = 500 
	money                  = 70 
	transports             = 130 
	escorts                = 20 
  
   
   diplomacy = 
   {   
  relation = {  tag = ENG value = 50 access = yes  }  
  relation = {  tag = TIB value = 150 guaranteed = {  day = 29 month = december year = 1936 }
  }  
    } 
   nationalprovinces      = {
  #Malaysia                 
  1406 1407 1408 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418 1419 1420 1421 1439 1440 1441 1442 1443 1445 1450 1455 1458
  #India  
  1444 1446 1447 1448 1449 1451 1452 1453 1454 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1473 1474 1475 1476 1477 1478 1479 1480 1481 1482 1483 1484 1485 1486 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 1503 1504 1505 1506 1507 1508 1512 1514 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528 1530 1531 1532 1535 1536 
  #Pakistan 
  1278 1529 1533 1534 1537 1538 1539 1540  
  1612
  } 
   ownedprovinces         = {   
  #Malaysia                 
  1406 1407 1408 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418 1419 1420 1421 1439 1440 1441 1442 1443 1445 1450 1455 1458
  #India  
  1444 1446 1447 1448 1449 1451 1452 1453 1454 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1473 1474 1475 1476 1477 1478 1479 1480 1481 1482 1483 1484 1485 1486 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 1503 1504 1505 1506 1507 1508 1512 1514 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528 1530 1531 1532 1535 1536 
  #Pakistan 
  1278 1529 1533 1534 1537 1538 1539 1540 
  1612
   } 
   controlledprovinces    = {    
  #Malaysia                 
  1406 1407 1408 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418 1419 1420 1421 1439 1440 1441 1442 1443 1445 1450 1455 1458
  #India  
  1444 1446 1447 1448 1449 1451 1452 1453 1454 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1473 1474 1475 1476 1477 1478 1479 1480 1481 1482 1483 1484 1485 1486 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 1503 1504 1505 1506 1507 1508 1512 1514 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528 1530 1531 1532 1535 1536 
  #Pakistan 
  1278 1529 1533 1534 1537 1538 1539 1540 
  1612
   } 
  
   SpyInfo                = {  country = "U02" NumberOfSpies = 3  } 
 
	# British Raj 1933 Techs
	techapps = {  
	# Infantry Division  
	1010  1020 1030 1040 1050 1060    
	# Mountain Division 
	1160  1170 1180 1190 1200 1210 1220 1230 1240   
	# Supply 
	1910 1920 1930 1940 1950 1960 1970 1980   
	# Cavalry Division 
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370
	# Armoured Car 
	2860 2870 2880 2020   
	# Field Artillery 
	2290 2300 2310 
	# Tank 
	7600 7610 2620 2010 
	# Engineers
	1830 1840 1850 1860
	# Static Anti-Air Artillery 
	2800 2450
	# Destroyer
	3010 3020 3030 3040
	# Light Cruiser 
	3110 3120 3130 3140
	# Heavy Cruiser 
	3210 3220 3230
	# Fighter 
	4500 4510 4520 4530 4540 4550 4010
	# Bomber 
	4600 4610 4620 4630 4120
	# Computers & cryptography
	5310 54010 54020 54030 5316 5326
	# Manufacturing
	5810 5820 5050 5830
	# Construction Engineering 
	5800 5080 5090 
	# Torpedo & ASW 18
	3720 3730 3736 3740 3750 3900
	# Troopships
	3810
	# Medicine
	5600
	# Naval Doctrines
	8010 8020 8050
	# Air Doctrines 
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 
	# Great War Land Doctrines (entente)
	6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910
	# Defensive Focus Grand Battleplan Path (FRA / UK)
	6560
	#Carrier Pigeons
	30020 30030
} 
	inventions = { 3000027 }
	policy = 
	{  date              = {  year = 0 month = january day = 0  } 
		democratic        = 5 
		political_left    = 3 
		freedom           = 3 
		free_market       = 5 
		professional_army = 2 # no conscription 
		defense_lobby     = 3 
		interventionism   = 3 
	} 

	headofstate            = {  type = 9 id = 825089  } #Freeman Freeman-Thomas of Willingdon
	headofgovernment       = {  type = 9 id = 825002  } 
   foreignminister        = {  type = 9 id = 825003  } 
   armamentminister       = {  type = 9 id = 825004  } 
   ministerofsecurity     = {  type = 9 id = 825005  } 
   ministerofintelligence = {  type = 9 id = 825006  } 
   chiefofstaff           = {  type = 9 id = 825007  } 
   chiefofarmy            = {  type = 9 id = 825008  } 
   chiefofnavy            = {  type = 9 id = 825009  } 
   chiefofair             = {  type = 9 id = 825010  } 
  
   landunit = 
   {  name     = "Southern Command" 
     location = 1516 
     id       = {  type = 12700 id = 9001  } 
     Division = 
     {  id       = {  type = 12700 id = 9002  } 
       name     = "4th Indian Division" 
       type     = infantry 
	   model    = 7
       strength = 100 
      } 
	Division = 
     {  id       = {  type = 12700 id = 9003  } 
       name     = "4th Indian Cavalry Brigade" 
       type     = cavalry 
	   model    = 8
       strength = 15 
       }   	  
    } 
   landunit = 
   {  name     = "Madras District" 
     location = 1500
     id       = {  type = 12700 id = 9004  } 
     Division = 
     {  id            = {  type = 12700 id = 9005  } 
       name          = "Madras Brigade" 
       type          = militia
	   model    = 2
       extra         = artillery 
       brigade_model = 1
       strength      = 80
       } 
    } 
   landunit = 
   {  name     = "Bombay District" 
     location = 1517
     id       = {  type = 12700 id = 9006  } 
     Division = 
     {  id            = {  type = 12700 id = 9007  } 
       name          = "Mhow Brigade" 
       type          = militia
	   model    = 2
       extra         = artillery 
       brigade_model = 1
       strength      = 80
       } 
    } 
   landunit = 
   {  name     = "Deccan District" 
     location = 1503
     id       = {  type = 12700 id = 9008  } 
     Division = 
     {  id            = {  type = 12700 id = 9009  } 
       name          = "Deccan Brigade" 
       type          = militia
	   model    = 3
       extra         = artillery 
       brigade_model = 2
       strength      = 80
       } 
    } 
   landunit = 
   {  name     = "Poona Brigade Area" 
     location = 1516
     id       = {  type = 12700 id = 9010  } 
     Division = 
     {  id       = {  type = 12700 id = 9011  } 
       name     = "Poona Brigade" 
       type     = garrison
	   model    = 2
       strength = 80        
      } 
    } 
   landunit = 
   {  name     = "Eastern Command" 
     location = 1451 
     id       = {  type = 12700 id = 9012  } 
     Division = 
     {  id       = {  type = 12700 id = 9013  } 
       name     = "3rd Indian Division" 
       type     = infantry 
	   model    = 7
       strength = 100 
      } 
	Division = 
     {  id       = {  type = 12700 id = 9014  } 
       name     = "3rd Indian Cavalry Brigade" 
       type     = cavalry 
	   model    = 8
       strength = 15 
       }   	  
    } 
   landunit = 
   {  name     = "Presidency & Assam District" 
     location = 1447
     id       = {  type = 12700 id = 9015  } 
     Division = 
     {  id       = {  type = 12700 id = 9016  } 
       name     = "Eastern Bengal Brigade" 
       type     = militia
	   model    = 2
       extra         = artillery 
       brigade_model = 1
       strength      = 80        
      }
	       Division = 
     {  id       = {  type = 12700 id = 9017  } 
       name     = "Assam Brigade" 
       type     = militia
	   model    = 2
       strength = 80 
       } 	  
    } 
   landunit = 
   {  name     = "Lucnow District" 
     location = 1461
     id       = {  type = 12700 id = 9018  } 
     Division = 
     {  id       = {  type = 12700 id = 9019  } 
       name     = "Allahabad Brigade" 
       type     = militia
	   model    = 2
       extra         = artillery 
       brigade_model = 1
       strength      = 80        
      }
	       Division = 
     {  id       = {  type = 12700 id = 9020  } 
       name     = "Lucknow Brigade" 
       type     = militia
	   model    = 2
       strength = 80 
       } 	  
    } 
   landunit = 
   {  name     = "Delhi Brigade Area" 
     location = 1459
     id       = {  type = 12700 id = 9021  } 
     Division = 
     {  id       = {  type = 12700 id = 9022  } 
       name     = "Delhi Brigade" 
       type     = garrison
	   model    = 2
       strength = 80        
      } 
    } 
   landunit = 
   {  name     = "Meerut District" 
     location = 1460 
     id       = {  type = 12700 id = 9023  } 
     Division = 
     {  id       = {  type = 12700 id = 9024  } 
       name     = "Meerut Brigade" 
       type          = militia
	   model    = 3
       extra         = artillery 
       brigade_model = 2
       strength      = 80
      } 
    } 
   landunit = 
   {  name     = "Zhob Brigade Area" 
     location = 1529
     id       = {  type = 12700 id = 9025  } 
     Division = 
     {  id       = {  type = 12700 id = 9026  } 
       name     = "Zhob Brigade" 
       type     = garrison
	   model    = 2
       strength = 80        
      } 
    } 
   landunit = 
   {  name     = "Baluchistan District" 
     location = 1529
     id       = {  type = 12700 id = 9027  } 
     Division = 
     {  id       = {  type = 12700 id = 9028  } 
       name     = "Quetta Brigade" 
       type     = militia
	   model    = 3
       extra         = artillery 
       brigade_model = 2
       strength      = 80        
      }
	       Division = 
     {  id       = {  type = 12700 id = 9029  } 
       name     = "Khojak Brigade" 
       type     = militia
	   model    = 3
       strength = 80 
       } 	  
    } 
   landunit = 
   {  name     = "Sind Brigade Area" 
     location = 1533
     id       = {  type = 12700 id = 9030  } 
     Division = 
     {  id       = {  type = 12700 id = 9031  } 
       name     = "Sind Brigade" 
       type     = garrison
	   model    = 2
       strength = 80        
      } 
    } 
   landunit = 
   {  name     = "Northern Command" 
     location = 1534
     id       = {  type = 12700 id = 9032  } 
     Division = 
     {  id       = {  type = 12700 id = 9033  } 
       name     = "1st Indian Division" 
       type     = infantry 
	   model    = 7
       strength = 100 
      } 
     Division = 
     {  id       = {  type = 12700 id = 9034  } 
       name     = "2nd Indian Division" 
       type     = infantry 
	   model    = 7
       strength = 100 
      } 
	Division = 
     {  id       = {  type = 12700 id = 9035  } 
       name     = "2nd Indian Cavalry Brigade" 
       type     = cavalry 
	   model    = 8
       strength = 15 
       }   	  
    } 
   landunit = 
   {  name     = "Lahore District" 
     location = 1530
     id       = {  type = 12700 id = 9036  } 
     Division = 
     {  id       = {  type = 12700 id = 9037  } 
       name     = "Sialkot Brigade" 
       type     = militia
	   model    = 3
       extra         = artillery 
       brigade_model = 2
       strength      = 80        
      }
	Division = 
     {  id       = {  type = 12700 id = 9038  } 
       name     = "Ferozepore Brigade" 
       type     = militia
	   model    = 3
       strength = 80 
       } 	
	Division = 
     {  id       = {  type = 12700 id = 9039  } 
       name     = "Jullundur Brigade" 
       type     = militia
	   model    = 3
       strength = 80 
       } 	
	Division = 
     {  id       = {  type = 12700 id = 9040  } 
       name     = "Lahore Brigade" 
       type     = militia
	   model    = 3
       strength = 80 
       } 	
	Division = 
     {  id       = {  type = 12700 id = 9041  } 
       name     = "Ambala Brigade" 
       type     = militia
	   model    = 3
       strength = 80 
       } 	  
    } 
   landunit = 
   {  name     = "Waziristan District" 
     location = 1537
     id       = {  type = 12700 id = 9042  } 
     Division = 
     {  id       = {  type = 12700 id = 9043  } 
       name     = "Razmak Brigade" 
       type     = militia
	   model    = 2
       extra         = artillery 
       brigade_model = 1
       strength      = 80
      } 
	Division = 
     {  id       = {  type = 12700 id = 9044  } 
       name     = "Bannu Brigade" 
       type     = militia
	   model    = 2
       strength = 80 
       } 
	Division = 
     {  id       = {  type = 12700 id = 9045  } 
       name     = "Wana Brigade" 
       type     = militia
	   model    = 2
       strength = 80 
       } 		  
    } 
   landunit = 
   {  name     = "Kohat District" 
     location = 1537
     id       = {  type = 12700 id = 9046  } 
     Division = 
     {  id       = {  type = 12700 id = 9047  } 
       name     = "Thal Brigade" 
       type     = militia
		model    = 2	   
       strength = 80
       extra         = artillery 
       brigade_model = 1        
      } 
	Division = 
     {  id       = {  type = 12700 id = 9048  } 
       name     = "Kohat Brigade" 
       type     = militia
	   model    = 2
       strength = 80 
       } 	
    } 
   landunit = 
   {  name     = "Peshawar District" 
     location = 1537
     id       = {  type = 12700 id = 9049  } 
     Division = 
     {  id       = {  type = 12700 id = 9050  } 
       name     = "Landikotal Brigade" 
       type     = militia
		model    = 3	   
       strength = 80
       extra         = artillery 
       brigade_model = 2        
      } 
	Division = 
     {  id       = {  type = 12700 id = 9051  } 
       name     = "Peshawar Brigade" 
       type     = militia
	   model    = 3
       strength = 80 
       } 
	Division = 
     {  id       = {  type = 12700 id = 9052  } 
       name     = "Nowshera Brigade" 
       type     = militia
	   model    = 3
       strength = 80 
       } 	
	Division = 
     {  id       = {  type = 12700 id = 9053  } 
       name     = "1st Indian Cavalry Brigade" 
       type     = cavalry 
	   model    = 8
       strength = 15 
       }   	  	
    } 
   landunit = 
   {  name     = "Rawalpindi District" 
     location = 1534
     id       = {  type = 12700 id = 9054  } 
     Division = 
     {  id       = {  type = 12700 id = 9055  } 
       name     = "Rawalpindi Brigade" 
       type     = militia
		model    = 3	   
       strength = 80
       extra         = artillery 
       brigade_model = 2        
      } 
    } 

   landunit = 
   {  name     = "Jammu & Kashmir State Forces" 
     location = 1540
     id       = {  type = 12700 id = 9056  } 
     Division = 
     {  id       = {  type = 12700 id = 9057  } 
       name     = "Jammu Brigade" 
       type     = militia
	   model    = 2
       strength = 100 
	locked = yes
      } 
     Division = 
     {  id       = {  type = 12700 id = 9058  } 
       name     = "Kashmir Brigade" 
       type     = militia
	   model    = 2
       strength = 100 
	locked = yes
      } 
    } 
   landunit = 
   {  name     = "Gwalior State Forces" 
     location = 1523
     id       = {  type = 12700 id = 9059  } 
	Division = 
     {  id       = {  type = 12700 id = 9060  } 
       name     = "Gwalior Cavalry Brigade" 
       type     = cavalry 
	   model    = 6
       strength = 45 
	locked = yes
       }   	 
     Division = 
     {  id       = {  type = 12700 id = 9061  } 
       name     = "Gwalior Infantry Brigade" 
       type     = militia
	   model    = 2
       strength = 100 
	locked = yes
      } 
    } 
   landunit = 
   {  name     = "Hyderabad State Forces" 
     location = 1487
     id       = {  type = 12700 id = 9062  } 
     Division = 
     {  id       = {  type = 12700 id = 9063  } 
       name     = "Hyderabad State Forces" 
       type     = militia
	   model    = 2
       strength = 100 
	locked = yes
      } 
    } 
   landunit = 
   {  name     = "Bikaner State Forces" 
     location = 1527
     id       = {  type = 12700 id = 9064  } 
     Division = 
     {  id       = {  type = 12700 id = 9065  } 
       name     = "Bikaner State Forces" 
       type     = militia
	   model    = 2
       strength = 80
	locked = yes
      } 
    } 
   landunit = 
   {  name     = "Patiala State Forces" 
     location = 1531
     id       = {  type = 12700 id = 9066  } 
     Division = 
     {  id       = {  type = 12700 id = 9067  } 
       name     = "Patiala State Forces" 
       type     = militia
	   model    = 2
       strength = 80
	locked = yes
      } 
    } 
   landunit = 
   {  name     = "Mysore State Forces" 
     location = 1507
     id       = {  type = 12700 id = 9068  } 
     Division = 
     {  id       = {  type = 12700 id = 9069  } 
       name     = "Mysore State Forces" 
       type     = militia
	   model    = 2
       strength = 70
	locked = yes
      } 
    } 

   landunit = 
   {  name     = "Burma Independent District" 
     location = 1415
     id       = {  type = 12700 id = 9070  } 
     Division = 
     {  id       = {  type = 12700 id = 9071  } 
       name     = "Burma Brigade" 
       type     = militia
		model    = 2	   
       strength = 80
       extra         = artillery 
       brigade_model = 1        
      } 
    } 
  
	navalunit = { 
		id = { type = 12700 id = 9072 } 
		name = "Royal Indian Marine" 
		location = 1517 
		base = 1517 
		division = { 
			id = { type = 12700 id = 9073 } 
			name = "1st Transport Flotilla" 
			type = transport 
			model = 1
			} 
		}  
  }