#Germany
province = { 
	id = 184 #Konigsberg
	supplypool = 2
	oilpool = 1
}
#Belgium
province = { 
	id = 894 #Matadi
	supplypool = 2
}

#China
province = { 
	id = 1325 #Nanyang
	supplypool = 5000
}
province = { 
	id = 1344 #Anqing
	supplypool = 300
}
province = { 
	id = 1345 #Hangzhou
	supplypool = 1000
}
#Dutch East Indies
province = { 
	id = 1616 #Koepang
	supplypool = 2
}
#Dutch East Indies
province = { 
	id = 1620 #Halmahera
	supplypool = 2
}
province = { 
	id = 1633 #Bandjarmasin
	supplypool = 2
}
province = { 
	id = 1638 #Bengkulu
	supplypool = 3
}
province = { 
	id = 1659 #Manado
	supplypool = 3
}
#France
province = { 
	id = 728 #Oran
	supplypool = 5000
	oilpool = 100
}
province = { 
	id = 1002 #Tamatave
	supplypool = 200
}
province = { 
	id = 1768 #Martinique
	supplypool = 200
}
#Greece
province = { 
	id = 382 #Irakleio
	supplypool = 3
}
province = { 
	id = 383 #Mitylene
	supplypool = 3
}
#Italy
province = { 
	id = 435 #Sassari
	supplypool = 2
}
province = { 
	id = 765 #Tobruk
	supplypool = 5
	oilpool = 5
}
province = { 
	id = 378 #Kalymnos
	supplypool = 2
	oilpool = 2
}
province = { 
	id = 815 #Massawa
	supplypool = 20
	oilpool = 5
}
province = { 
	id = 836 #Mogadishu
	supplypool = 10
	oilpool = 5
}
#Japan
province = { 
	id = 1219 #Port Arthur
	supplypool = 2
	oilpool = 2
}
province = { 
	id = 1245 #Tangshan
	supplypool = 50
	oilpool = 5
}
province = { 
	id = 1338 #Shanghai
	supplypool = 50
	oilpool = 5
}
province = { 
	id = 1362 #Taibei
	supplypool = 50
	oilpool = 5
}
#Portugal
province = { 
	id = 892 #Lobito
	supplypool = 2
}
province = { 
	id = 1513 #Panjim
	supplypool = 2
}
#Spain
province = { 
	id = 475 #Palma de Mallorca
	supplypool = 2
}
province = { 
	id = 715 #Tangiers
	supplypool = 5
}
province = { 
	id = 990 #Canaria
	supplypool = 5
	oilpool = 5
}
province = { 
	id = 988 #Villa Cisneros
	supplypool = 2
}
province = { 
	id = 913 #Bata
	supplypool = 2
}
#Sweden
province = { 
	id = 2156 #Visby
	supplypool = 2
}
#United Kindgom
province = { 
	id = 348 #Gibraltar
	supplypool = 2
}
province = { 
	id = 429 #Malta
	supplypool = 2
}
province = { 
	id = 832 #Hargeisa
	supplypool = 3
}
province = { 
	id = 839 #Garissa
	supplypool = 3
}
province = { 
	id = 929 #Lagos
	supplypool = 2
}
province = { 
	id = 956 #Accra
	supplypool = 2
}
province = { 
	id = 964 #Freetown
	supplypool = 2
}
province = { 
	id = 1008 #Tel Aviv
	supplypool = 2
}
province = { 
	id = 1371 #Hong Kong
	supplypool = 2
}
province = { 
	id = 1432 #Singapore
	supplypool = 2
}
province = { 
	id = 1511 #Colombo
	supplypool = 2
}
province = { 
	id = 1728 #Suva
	supplypool = 2
}
province = { 
	id = 1773 #The Bermudas
	supplypool = 2
}
province = { 
	id = 1782 #Jamaica
	supplypool = 2
}
#USA
province = { 
	id = 889 #Balboa
	supplypool = 5
	oilpool = 5
}
province = { 
	id = 1565 #Manila
	supplypool = 2
}
province = { 
	id = 1734 #Pearl Harbour
	supplypool = 5
	oilpool = 5
}
province = { 
	id = 1765 #Puerto Rico
	supplypool = 2
}

