 # Ministres OK
 # OOB OK

 ############################## 
 # Country definition for FRA # 
 ############################## 
 
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = FRA 
	ai = "fra_1936.ai"
	ai_settings	= { flags = { FRABuildStandard = yes MOB1 = yes MOB2 = yes MOB3 = yes MOB4 = yes MOB5 = yes } }
	capital                = 55 
	# Resource Reserves 
	energy                 = 7440
	metal                  = 3720
	rare_materials         = 1860
	oil                    = 5000 
	supplies               = 16500 
	money                  = 50 
	manpower               = 10 
	transports             = 570 
	escorts                = 60 
	dissent =  15

   diplomacy = 
   {  relation = {  tag = AST value = 150  } 
     relation = {  tag = AUS value = -10  } 
     relation = 
     {  tag        = BEL 
       value      = 120 
       guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = BHU value = 150  } 
     relation = {  tag = BUL value = 20  } 
     relation = {  tag = CAN value = 150  } 
     relation = {  tag = CZE value = 150  } 
     relation = {  tag = ENG value = 150  } 
     relation = {  tag = EST value = 65  } 
     relation = {  tag = ETH value = 25  } 
     relation = {  tag = FIN value = 85  } 
     relation = {  tag = GER value = -35  } 
     relation = {  tag = GRE value = 20  } 
     relation = 
     {  tag        = HOL 
       value      = 75 
       guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = HUN value = -70  } 
     relation = {  tag = IRE value = 25  } 
     relation = {  tag = IRQ value = 100  } 
     relation = {  tag = ITA value = -50  } 
     relation = {  tag = JAP value = -20  } 
     relation = {  tag = LAT value = 65  } 
     relation = {  tag = LIT value = 65  } 
     relation = 
     {  tag        = LUX 
       value      = 120 
       guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = NEP value = 150  } 
     relation = 
     {  tag        = NOR 
       guaranteed = {  day = 29 month = december year = 1932  }  
      } 
     relation = {  tag = NZL value = 150  } 
     relation = {  tag = OMN value = 150  } 
     relation = 
     {  tag        = POL 
       value      = 100 
       guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = ROM value = 50  } 
     relation = {  tag = SAF value = 150  } 
     relation = {  tag = SAU value = 10  } 
     relation = 
     {  tag        = SCH 
       value      = 1 
       guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = SIA value = -100  } 
     relation = {  tag = SOV value = 0  } # 100
     relation = {  tag = SPR value = 10  } 
     relation = 
     {  tag        = TUR 
       value      = 50 
       guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = U03 value = 50 access = yes  }  
     relation = {  tag = U04 value = 50 access = yes  }  
     relation = {  tag = USA value = 65  } 
     relation = {  tag = YEM value = 150  } 
     relation = 
     {  tag        = YUG 
       value      = 50 
       guaranteed = {  day = 29 month = december year = 1932  } 
      } 
    } 
   SpyInfo                = {  country = "FRA" NumberOfSpies = 9  } 
   # Togoland 
   # Metropolitan France 
   nationalprovinces      = { 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 
          
                             } 
   # Metropolitan France 
   ownedprovinces         = {  37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 717 718 719 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738 739 740 741 742 743 744 745 746 747 748 749 833 907 908 909 910 911 914 915 917 918 919 920 921 922 923 924 925 926 927 928 942 943 944 945 946 947 948 949 950 951 957 958 959 960 961 962 965 966 967 968 970 971 972 973 974 975 976 977 978 980 981 982 983 984 985 986 996 999 1000 1001 1002 1003 1581 1582 1583 1584 1585 1586 1730 1740 1743 1744 1752 1767 1768 2000 2135 
	127 # Saar occupation
                             } 
   # Togoland 
   # Metropolitan France 
   controlledprovinces    = {  37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 717 718 719 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738 739 740 741 742 743 744 745 746 747 748 749 833 907 908 909 910 911 914 915 917 918 919 920 921 922 923 924 925 926 927 928 942 943 944 945 946 947 948 949 950 951 957 958 959 960 961 962 965 966 967 968 970 971 972 973 974 975 976 977 978 980 981 982 983 984 985 986 996 999 1000 1001 1002 1003 1581 1582 1583 1584 1585 1586 1730 1740 1743 1744 1752 1767 1768 2000 2135 
	127 # Saar occupation
                             }
	claimedprovinces = {
                            717 718 719 720 721 722 723 724 725 726 #Morocco 
                            727 728 729 730 731 732 733 734 735 736 737 738 739 743 #Algeria
                            740 741 742 744 745 746 747 748 749 # Tunisia
                            907 908 909 910 911 914 915 917 918 919 #French Congo and Cameroon
                            920 921 922 923 924 925 926 927 928 #Central Africa
                            942 943 944 945 946 947 #Niger
                            948 949 950 951 #Slave Coast
                            957 958 959 #Volta
                            960 961 962 #Ivory Coast
                            965 966 967 968 970 #Guinean Coast
                            971 972 973 974 975 976 977 #Malian Valleys
                            978 980 #Senegambia
                            981 982 983 #Mauretania
                            984 985 986 #Malian Desert
                            833 #Djbouti
                            1001 1002 1003 996 999 1000 #Madagascar + nearby Island
                            
                            2000  #Cayenne 
                            1752 1767 1768 #French West Indies
                            1581 1582 1583 1584 1585 1586 1730 1740 1743 1744 #French Pacific Island
                            2135 #Saint Pierre island near Newfoundland
						}		 
		 
   # FRA 1933 techs 
   # ###################### 
   techapps = { 
#Basic Armoured Car  
2860 2870 2880 2020
#Early Tank 
7600 7610 2620 2010 2630 2640 2646
#Great War Heavy Field Artillery 
2290 2300 2310 2900
#Early Static Anti-Air Artillery 
2800 2450 21180 21190
#Basic Anti-Air Artillery Brigade 
2810 2820 2510
#Early Anti-Tank Artillery 
##2400
#Early Infantry Division  
1010  1020 1030 1040 1050 1060 1070 1080 1090
#1930 Cavalry Division  
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370
#Early Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240
#Naval Infantry
1560
#Engineers
1830 1840 1850 1860
#Interbellum 1930 Supply 
1910 1920 1930 1940 1950 1960 1970 1980
#Modern Agriculture 
5700 5710 5010
#Basic Machine Tools 
5810 5820 5050 5830 5060
#Improved Construction Engineering 
5800 5080 5090 
#improved Oil Refining #5190

#Computers 
5310 54010 54020 54030
#cryptografi
5316 5326
#Medicine
5600 5610 5620 5630
#Exp. Rocket
5560

# Destroyer 
3010 3020 3030 3040 3050
# Light Cruiser 
3110 3120 3130 3140 3150
# Heavy Cruiser 
3210 3220 3230 3240 3250 
# Battleship 
3410 3420 3430 3440 3450 3456 3460
#Great War Air Carrier 
3510
#Improved Light carrier 
12100 12110 12120
#Short Range Submarine 
3610 3620 3630 3640
# Battle Cruiser
3310 3320 3330
#Torpedo & ASW 18
3720 3730 3736 3740 3750 3900
#Troopships
3810 3820

#Early Fighter  
4500 4510 4520 4530 4540 4550 4010 4020
#Early Bomber 
4600 4610 4620 4630 4120 4130
#Multirole fighter
4300 4310 4320 4330
#SEAPLANES
4740 4750 4760 4770
#ww1 strategic bomber
4800 4810 4820
#ww1 navalbomber
4700 4710
#CAG 30
4900 4910
#Great War Hospital System 
14000 14010 14020

# Great War Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910
#Land Doctrines
6560

#Naval Doctrines
# Theories
8010 8020 8030 8040 8050 8060 8070 8080 
# Amphibious Warfare
82300
# Naval Logistics
82500
# Naval Interdiction
8500 8510 8550 8600 
# Engagement Tactic (Fleet-in-Being)
8900 8910 8920 8930 8940
# Naval Supremacy
8100 8110 8120 8150 8160 8200 8210

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470
#Carrier Pigeons
30020 30030
} 
inventions = { 3000027 }
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 9 
     political_left    = 6 
     free_market       = 9 
     freedom           = 10 
     professional_army = 5 
     defense_lobby     = 7 
     interventionism   = 5 
    } 
	peacetime_ic_mod       = 0.3 # +0.8 from 6 events pre-war
    industrial_modifier = 0.82 # 1929 crisis (1.12-0.1); Restored by events 2002076(Economic Recovery Policy) +2% and 2002077(Unemployment rate down to 10 percent) +8%
   headofstate            = {  type = 9 id = 5001  } # Albert Lebrun
   headofgovernment       = {  type = 9 id = 5020  } # Edouard Daladier
   foreignminister        = {  type = 9 id = 5031  } # Joseph Paul Boncour
   armamentminister       = {  type = 9 id = 5049  } # Georges Bonnet
   ministerofsecurity     = {  type = 9 id = 5095  } # Camille Chautemps
   ministerofintelligence = {  type = 9 id = 5395  } # Marie-Louis Koëltz
   chiefofstaff           = {  type = 9 id = 5124  } # Maxime Weygand
   chiefofarmy            = {  type = 9 id = 5136  } # Maxime Weygand
   chiefofnavy            = {  type = 9 id = 5397  } # Georges Durand-Viel
   chiefofair             = {  type = 9 id = 5010  } # Victor Denain
   # #################
   # ###FRENCH OOB####
   # #################
   landunit = 
   {  id       = {  type = 13500 id = 1  } 
     name     = "Région militaire de Paris" 
     leader   = 5076 # Gamelin
     location = 55 
     Division = 
     {  id       = {  type = 13500 id = 201  } 
       name     = "Grand Quartier Général" 
       type     = hq 
       model    = 2 
       strength = 50 
	extra = engineer
	brigade_model = 2
      } 
     Division = 
     {  id    = {  type = 13500 id = 2  } 
       name  = "10ème Division d'Infanterie" 
       type  = infantry 
	   model = 7
	strength = 75
      } 
     Division = 
     {  id   = {  type = 13500 id = 3  } 
       name = "3ème Division d'Infanterie Coloniale" 
       type = infantry 
	   model = 7
	strength = 75
      } 
     Division = 
     {  id    = {  type = 13500 id = 4  } 
       name  = "5ème Division de Cavalerie" 
       strength = 75
       type  = cavalry
       model = 8
       extra    = light_armor_brigade 
	   brigade_model = 2
      } 
     Division = 
     {  id       = {  type = 13500 id = 5  } 
       name     = "3ème Division de Cavalerie" 
       type     = cavalry 
       model    = 8 
       extra    = light_armor_brigade 
	   brigade_model = 1
       strength = 75 
      } 
     Division = 
     {  id    = {  type = 13500 id = 6  } 
       name  = "41ème Division d'Infanterie" 
       strength = 10
       type  = infantry 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 7  } 
       name  = "71ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 8  } 
     name     = "Corps d'Armée Colonial" 
     location = 55 
     Division = 
     {  id    = {  type = 13500 id = 9  } 
       name  = "5ème Division d'Infanterie Coloniale" 
       strength = 10
       type  = infantry 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 10  } 
       name  = "6ème Division d'Infanterie Coloniale"
       strength = 10 
       type  = infantry 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 11  } 
       name  = "7ème Division d'Infanterie Coloniale" 
       strength = 10
       type  = infantry 
	   model = 6
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 12  } 
     name     = "Ier Corps d'Armée" 
     location = 52 
     Division = 
     {  id    = {  type = 13500 id = 13  } 
       name  = "1ère Division d'Infanterie Motorisée" 
       type  = infantry 
       model = 7 
       extra = armored_car 
	   brigade_model = 2
	strength = 75
      } 
     Division = 
     {  id    = {  type = 13500 id = 14  } 
       name  = "2ème Division d'Infanterie" 
       strength = 10 
       type  = infantry 
	   model = 6
      }
     Division = 
     {  id    = {  type = 13500 id = 15  } 
       name  = "51ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    }
   landunit = 
   {  id       = {  type = 13500 id = 16  } 
     name     = "IIème Corps d'Armée" 
     location = 50 
     Division = 
     {  id   = {  type = 13500 id = 17  } 
       name = "4ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id       = {  type = 13500 id = 18  } 
       name     = "3ème Division d'Infanterie Motorisée" 
       strength = 75 
       type     = infantry 
       model    = 7 
       extra    = armored_car 
	   brigade_model = 2
      }
     Division = 
     {  id    = {  type = 13500 id = 19  } 
       name  = "52ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 20  } 
     name     = "IIIème Corps d'Armée" 
     location = 45 
     Division = 
     {  id   = {  type = 13500 id = 21  } 
       name = "6ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id       = {  type = 13500 id = 22  } 
       name     = "5ème Division d'Infanterie Motorisée" 
       strength = 75 
       type     = infantry 
       model    = 7 
       extra    = armored_car 
	   brigade_model = 2
      }
     Division = 
     {  id    = {  type = 13500 id = 23  } 
       name  = "53ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 24  } 
     name     = "IVème Corps d'Armée" 
     location = 58 
     Division = 
     {  id   = {  type = 13500 id = 25  } 
       name = "19ème Division d'Infanterie" 
       type = infantry
	   model = 7
       strength = 75 
      } 
     Division = 
     {  id   = {  type = 13500 id = 26  } 
       name = "7ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id   = {  type = 13500 id = 27  } 
       name = "20ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id    = {  type = 13500 id = 28  } 
       name  = "54ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 29  } 
     name     = "Vème Corps d'Armée" 
     location = 66 
     Division = 
     {  id       = {  type = 13500 id = 30  } 
       name     = "1ère Division de Cavalerie" 
       type     = cavalry 
       model    = 8 
       extra    = light_armor_brigade 
	   brigade_model = 1
       strength = 75 
      } 
     Division = 
     {  id       = {  type = 13500 id = 31  } 
       name     = "9ème Division d'Infanterie Motorisée" 
       strength = 75 
       type     = infantry 
	   model = 7
       extra    = armored_car 
	   brigade_model = 2
      } 
     Division = 
     {  id   = {  type = 13500 id = 32  } 
       name = "45ème Division d'Infanterie" 
       strength = 10
       type = infantry 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 33  } 
       name  = "55ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 34  } 
     name     = "VIème Corps d'Armée" 
     location = 104 
     Division = 
     {  id       = {  type = 13500 id = 35  } 
       name     = "42ème Division d'Infanterie" 
       type     = infantry 
	   model = 7
       extra    = artillery 
	   brigade_model = 3
       strength = 75 
      } 
     Division = 
     {  id       = {  type = 13500 id = 36  } 
       name     = "2ème Division d'Infanterie Nord-Africaine" 
       type     = infantry 
	   model = 7
       strength = 75 
      } 
     Division = 
     {  id    = {  type = 13500 id = 37  } 
       name  = "55ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 38  } 
     name     = "VIIème Corps d'Armée" 
     location = 97 
     Division = 
     {  id       = {  type = 13500 id = 39  } 
       name     = "13ème Division d'Infanterie" 
       type     = infantry 
	   model = 7
       strength = 75 
      } 
     Division = 
     {  id       = {  type = 13500 id = 40  } 
       name     = "14ème Division d'Infanterie" 
       type     = infantry 
	   model = 7
       strength = 75 
       extra    = artillery 
	   brigade_model = 3
      } 
     Division = 
     {  id   = {  type = 13500 id = 41  } 
       name = "47ème Division d'Infanterie" 
       strength = 10
       type = infantry 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 42  } 
       name  = "57ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 43  } 
     name     = "VIIIème Corps d'Armée" 
     location = 64 
     Division = 
     {  id   = {  type = 13500 id = 44  } 
       name = "16ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id       = {  type = 13500 id = 45  } 
       name     = "15ème Division d'Infanterie Motorisée" 
       strength = 75 
       type     = infantry 
       model    = 7 
       extra    = armored_car 
	   brigade_model = 2
      }
     Division = 
     {  id    = {  type = 13500 id = 46  } 
       name  = "58ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 47  } 
     name     = "IXème Corps d'Armée" 
     location = 61 
     Division = 
     {  id       = {  type = 13500 id = 48  } 
       name     = "23ème Division d'Infanterie" 
       type     = infantry 
	   model = 7
       strength = 75 
      } 
     Division = 
     {  id       = {  type = 13500 id = 49  } 
       name     = "3ème Division d'Infanterie Nord-Africaine" 
       type     = infantry 
	   model = 6
       strength = 10 
      } 
     Division = 
     {  id    = {  type = 13500 id = 50  } 
       name  = "18ème Division d'Infanterie"
       strength = 10 
       type  = infantry 
	   model = 6
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 51  } 
     name     = "Xème Corps d'Armée" 
     location = 107 
     Division = 
     {  id       = {  type = 13500 id = 52  } 
       name     = "43ème Division d'Infanterie" 
       type     = infantry 
	   model = 7
       strength = 75 
      } 
     Division = 
     {  id    = {  type = 13500 id = 53  } 
       name  = "60ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 54  } 
     name     = "XIème Corps d'Armée" 
     location = 57 
     Division = 
     {  id       = {  type = 13500 id = 55  } 
       name     = "21ème Division d'Infanterie" 
       type     = infantry 
	   model = 7
       strength = 75 
      } 
     Division = 
     {  id   = {  type = 13500 id = 56  } 
       name = "22ème Division d'Infanterie" 
       strength = 10
       type = infantry 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 57  } 
       name  = "61ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 58  } 
     name     = "XIIème Corps d'Armée" 
     location = 99 
     Division = 
     {  id    = {  type = 13500 id = 59  } 
       name  = "4ème Division de Cavalerie" 
       strength = 75
       type  = cavalry 
       model = 8
	       extra    = light_armor_brigade 
	   brigade_model = 2
      } 
     Division = 
     {  id   = {  type = 13500 id = 60  } 
       name = "24ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id       = {  type = 13500 id = 61  } 
       name     = "12ème Division d'Infanterie Motorisée" 
       strength = 75 
       type     = infantry 
       model    = 7 
       extra    = armored_car 
	   brigade_model = 2
      }
     Division = 
     {  id    = {  type = 13500 id = 62  } 
       name  = "62ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 63  } 
     name     = "XIIIème Corps d'Armée" 
     location = 71 
     Division = 
     {  id   = {  type = 13500 id = 64  } 
       name = "26ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id       = {  type = 13500 id = 65  } 
       name     = "25ème Division d'Infanterie Motorisée" 
       strength = 75 
       type     = infantry 
       model    = 7 
       extra    = armored_car 
	   brigade_model = 2
      }
     Division = 
     {  id    = {  type = 13500 id = 66  } 
       name  = "63ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 67  } 
     name     = "XIVème Corps d'Armée" 
     location = 85 
     Division = 
     {  id   = {  type = 13500 id = 68  } 
       name = "27ème Division d'Infanterie Alpine" 
       type = bergsjaeger 
	   model = 7
       extra    = artillery 
	   brigade_model = 3
	strength = 75
      } 
     Division = 
     {  id   = {  type = 13500 id = 69  } 
       name = "28ème Division d'Infanterie Alpine" 
       strength = 10
       type = bergsjaeger 
	   model = 6
      } 
     Division = 
     {  id   = {  type = 13500 id = 70  } 
       name = "64ème Division d'Infanterie Alpine" 
       strength = 5
       type = bergsjaeger 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 71  } 
       name     = "1ère Division d'Infanterie Nord-Africaine" 
       type     = infantry 
	   model = 7
	strength = 75
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 72  } 
     name     = "XVème Corps d'Armée" 
     location = 89 
     Division = 
     {  id   = {  type = 13500 id = 73  } 
       name = "29ème Division d'Infanterie Alpine" 
       type = bergsjaeger 
	   model = 7
	strength = 75
      } 
     Division = 
     {  id   = {  type = 13500 id = 74  } 
       name = "30ème Division d'Infanterie Alpine" 
       strength = 10
       type = bergsjaeger 
	   model = 6
      } 
     Division = 
     {  id   = {  type = 13500 id = 75  } 
       name = "65ème Division d'Infanterie Alpine" 
       strength = 5
       type = bergsjaeger 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 76  } 
       name     = "2ème Division d'Infanterie Coloniale" 
       type     = infantry 
	   model = 7
       extra    = artillery 
	   brigade_model = 3
	strength = 75
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 77  } 
     name     = "XVIème Corps d'Armée" 
     location = 82 
     Division = 
     {  id   = {  type = 13500 id = 78  } 
       name = "32ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id   = {  type = 13500 id = 79  } 
       name = "31ème Division d'Infanterie Alpine" 
       type = bergsjaeger 
	   model = 7
	strength = 75
      } 
     Division = 
     {  id    = {  type = 13500 id = 80  } 
       name  = "66ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 81  } 
     name     = "XVIIème Corps d'Armée" 
     location = 77 
     Division = 
     {  id       = {  type = 13500 id = 82  } 
       name     = "4ème Division d'Infanterie Coloniale" 
       type     = infantry 
	   model = 7
	strength = 75
      } 
     Division = 
     {  id    = {  type = 13500 id = 83  } 
       name  = "67ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 84  } 
     name     = "XVIIIème Corps d'Armée" 
     location = 68 
     Division = 
     {  id       = {  type = 13500 id = 85  } 
       name     = "1ère Division d'Infanterie Coloniale" 
       type     = infantry 
	   model = 7
	strength = 75
      } 
     Division = 
     {  id   = {  type = 13500 id = 86  } 
       name = "36ème Division d'Infanterie"
       type = infantry 
	   model = 7
	extra = artillery
	brigade_model = 3
	strength = 75
      }
     Division = 
     {  id   = {  type = 13500 id = 87  } 
       name = "35ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 88  } 
     name     = "XXème Corps d'Armée" 
     location = 106 
     Division = 
     {  id       = {  type = 13500 id = 89  } 
       name     = "QG Théâtre d'Opérations Nord-Est" 
       type     = hq 
       model    = 2
       strength = 50 
	extra = engineer
	brigade_model = 2
      } 
     Division = 
     {  id       = {  type = 13500 id = 90  } 
       name     = "2ème Division de Cavalerie" 
       type     = cavalry 
       model    = 8 
       extra    = light_armor_brigade 
	   brigade_model = 1
	strength = 75
      } 
     Division = 
     {  id       = {  type = 13500 id = 91  } 
       name     = "11ème Division d'Infanterie" 
       type     = infantry 
	   model = 7
	strength = 75
      } 
     Division = 
     {  id   = {  type = 13500 id = 92  } 
       name = "4ème Division d'Infanterie Nord-Africaine" 
       type = infantry 
	   model = 6
	strength = 10
      } 
     Division = 
     {  id    = {  type = 13500 id = 93  } 
       name  = "70ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 94  } 
     name     = "Division d'Alger" 
     location = 727 
     Division = 
     {  id   = {  type = 13500 id = 95  } 
       name = "Division d'Alger" 
       type = infantry 
	   model = 6
       extra    = cavalry_brigade 
	   brigade_model = 6
      } 
    }
   landunit = 
   {  id       = {  type = 13500 id = 96  } 
     name     = "Division d'Oran" 
     location = 728 
     Division = 
     {  id   = {  type = 13500 id = 97  } 
       name = "Division d'Oran" 
       type = infantry 
	   model = 6
       extra    = cavalry_brigade 
	   brigade_model = 6
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 98  } 
     name     = "Division de Constantine" 
     location = 734 
     Division = 
     {  id   = {  type = 13500 id = 99  } 
       name = "Division de Constantine" 
       type = infantry 
	   model = 6
       extra    = cavalry_brigade 
	   brigade_model = 6
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 100  } 
     name     = "Division de Tunis" 
     location = 747 
     Division = 
     {  id   = {  type = 13500 id = 101  } 
       name = "Division de Tunis" 
       type = infantry 
	   model = 6
       extra    = cavalry_brigade 
	   brigade_model = 6
	strength = 90
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 102  } 
     name     = "Division de Sousse" 
     location = 745 
     Division = 
     {  id   = {  type = 13500 id = 103  } 
       name = "Division de Sousse" 
       type = garrison 
	   model = 3
	strength = 80
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 104  } 
     name     = "XIXème Région Militaire" 
     location = 727 
     Division = 
     {  id       = {  type = 13500 id = 105  } 
       name     = "81ème Division d'Infanterie d'Afrique" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 106  } 
       name     = "82ème Division d'Infanterie d'Afrique" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 107  } 
       name     = "83ème Division d'Infanterie d'Afrique" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 108  } 
       name     = "84ème Division d'Infanterie d'Afrique" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 109  } 
       name     = "85ème Division d'Infanterie d'Afrique" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 110  } 
       name     = "86ème Division d'Infanterie d'Afrique" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 111  } 
       name     = "87ème Division d'Infanterie d'Afrique" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 112  } 
     name     = "Commandement des troupes du Maroc" 
     location = 717 
     Division = 
     {  id       = {  type = 13500 id = 113  } 
       name     = "1ère Division Marocaine" 
       strength = 40 
       type     = infantry 
	   model = 5
       extra    = cavalry_brigade 
	   brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 13500 id = 114  } 
       name     = "2ème Division Marocaine" 
       strength = 40 
       type     = infantry 
	   model = 5
       extra    = cavalry_brigade 
	   brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 13500 id = 115  } 
       name     = "3ème Division Marocaine" 
       strength = 40 
       type     = infantry 
	   model = 5
       extra    = cavalry_brigade 
	   brigade_model = 6
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 116  } 
     name     = "Division de Fès" 
     location = 721 
     Division = 
     {  id   = {  type = 13500 id = 117  } 
       name = "Division de Fès" 
       type = garrison 
	   model = 3
	   locked = yes
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 318  } 
     name     = "Division de Marrakech" 
     location = 722 
     Division = 
     {  id   = {  type = 13500 id = 319  } 
       name = "Division de Marrakech" 
       type = garrison 
	   model = 3
	   locked = yes
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 320  } 
     name     = "Division de Meknès" 
     location = 717 
     Division = 
     {  id   = {  type = 13500 id = 321  } 
       name = "Division de Meknès" 
       type = garrison 
	   model = 3
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 322  } 
     name     = "Subdivision de Casablanca" 
     location = 718 
     Division = 
     {  id   = {  type = 13500 id = 323  } 
       name = "Subdivision de Casablanca" 
       type = militia 
	   model = 4
       extra    = cavalry_brigade 
	   brigade_model = 6
	   locked = yes
      }
     Division = 
     {  id   = {  type = 13500 id = 324  } 
       name = "Goumiers" 
       type = militia 
	   model = 3
       extra    = cavalry_brigade 
	   brigade_model = 5
      }
     Division = 
     {  id   = {  type = 13500 id = 337  } 
       name = "Maghzens" 
       type = militia 
	   model = 3
	strength = 80
      }
     Division = 
     {  id   = {  type = 13500 id = 338  } 
       name = "Partisans" 
       type = militia 
	   model = 3
	strength = 20
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 325  } 
     name     = "Troupes d'Afrique occidentale" 
     location = 978 
     Division = 
     {  id   = {  type = 13500 id = 326  } 
       name = "Point d'appui de la flotte de Dakar" 
       type = garrison 
	   model = 3
       strength = 20
	locked = yes
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 327  } 
     name     = "1ère Brigade de Tirailleurs Sénégalais" 
     location = 983 
     Division = 
     {  id       = {  type = 13500 id = 328  } 
       name     = "1ère Brigade de Tirailleurs Sénégalais" 
       type     = militia 
       model    = 4 
      } 
    }
   landunit = 
   {  id       = {  type = 13500 id = 329  } 
     name     = "2ème Brigade de Tirailleurs Sénégalais" 
     location = 976 
     Division = 
     {  id       = {  type = 13500 id = 330  } 
       name     = "2ème Brigade de Tirailleurs Sénégalais" 
       type     = militia 
       model    = 4 
      } 
    }
   landunit = 
   {  id       = {  type = 13500 id = 331  } 
     name     = "3ème Brigade de Tirailleurs Sénégalais" 
     location = 962 
     Division = 
     {  id       = {  type = 13500 id = 332  } 
       name     = "3ème Brigade de Tirailleurs Sénégalais" 
       type     = militia 
       model    = 4 
      } 
    }
   landunit = 
   {  id       = {  type = 13500 id = 333  } 
     name     = "Troupes d'Afrique équatoriale" 
     location = 920 
     Division = 
     {  id       = {  type = 13500 id = 334  } 
       name     = "Tirailleurs du Tchad" 
       type     = militia 
       model    = 4
	strength = 80 
      } 
    }
   landunit = 
   {  id       = {  type = 13500 id = 335  } 
     name     = "Troupes d'Afrique orientale" 
     location = 1001 
     Division = 
     {  id       = {  type = 13500 id = 336  } 
       name     = "Tirailleurs Malgaches" 
       type     = militia 
       model    = 4 
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 339  } 
     name     = "Troupes des Antilles" 
     location = 1768 
     Division = 
     {  id   = {  type = 13500 id = 340  } 
       name = "Troupes des Antilles" 
       type = garrison 
	   model = 3
       strength = 10
      }
    }
	# ############
	# French Navy
	# ############
	navalunit = { 
		id = { type = 13500 id = 118 } 
		name = "Flotte de la Méditerranée" 
		location = 86 
		base = 86 
		division = { 
			id = { type = 13500 id = 142 } 
			name = "Bretagne" 
			type = battleship 
			model = 3 
			extra1 = naval_anti_air_l
			brigade_model1 = 0
			} 
		division = { 
			id = { type = 13500 id = 122 } 
			name = "Provence" 
			type = battleship 
			model = 3 
			extra1 = naval_anti_air_l
			brigade_model1 = 0
			} 
		division = { 
			id = { type = 13500 id = 121 } 
			name = "Lorraine" 
			type = battleship 
			model = 3 
			extra1 = naval_anti_air_l
			brigade_model1 = 0
			extra2 = floatplane
			brigade_model2 = 5
			} 
		division = { 
			id = { type = 13500 id = 132 } 
			name = "Courbet" 
			type = battleship 
			model = 2 
			extra1 = naval_anti_air_l
			brigade_model1 = 0
			extra2 = naval_fire_controll_l
			brigade_model2 = 0
			} 
		division = { 
			id = { type = 13500 id = 141 } 
			name = "Jean Bart" 
			type = battleship 
			model = 2 
			extra1 = naval_anti_air_l
			brigade_model1 = 0
			extra2 = naval_fire_controll_l
			brigade_model2 = 0
			} 
		division = { 
			id = { type = 13500 id = 133 } 
			name = "Paris" 
			type = battleship 
			model = 2 
			extra1 = naval_anti_air_l
			brigade_model1 = 0
			extra2 = naval_fire_controll_l
			brigade_model2 = 0
			} 
		division = { 
			id = { type = 13500 id = 119 } 
			name = "Béarn" 
       			type          = escort_carrier  
        		model         = 2  
			} 
      		Division = {  id   = {  type = 14800 id = 341  }  
        		name = "Commandant Teste"  
       			type = escort_carrier  
			model = 0
			extra1 = naval_anti_air_l
			brigade_model1 = 0
		        } 
		division = { 
			id = { type = 13500 id = 123 } 
			name = "Colbert" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 124 } 
			name = "Dupleix" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 143 } 
			name = "Foch" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 135 } 
			name = "Duquesne" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 144 } 
			name = "Tourville" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 145 } 
			name = "7 Division de contre-torpilleurs" 
			type = destroyer 
			model = 4 
			} 
		division = { 
			id = { type = 13500 id = 146 } 
			name = "1 Division de torpilleurs" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 147 } 
			name = "3 Division de torpilleurs" 
			type = destroyer 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 148 } 
			name = "7 Division de torpilleurs" 
			type = destroyer 
			model = 3 
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 130 } 
		name = "Flotte de l'Atlantique" 
		location = 37 
		base = 37
 		division = { 
			id = { type = 13500 id = 342 } 
			name = "Diderot" 
			type = battleship 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 343 } 
			name = "Voltaire" 
			type = battleship 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 128 } 
			name = "Condé" 
			type = heavy_cruiser 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 344 } 
			name = "Gueydon" 
			type = heavy_cruiser 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 127 } 
			name = "Duguay-Trouin" 
			type = light_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 3
			} 
		division = { 
			id = { type = 13500 id = 129 } 
			name = "Lamotte-Picquet" 
			type = light_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 3
			} 
		division = { 
			id = { type = 13500 id = 125 } 
			name = "Metz" 
			type = light_cruiser 
			model = 2 
			} 
		division = { 
			id = { type = 13500 id = 131 } 
			name = "Thionville" 
			type = light_cruiser 
			model = 2 
			} 
		division = { 
			id = { type = 13500 id = 345 } 
			name = "Mulhouse" 
			type = light_cruiser 
			model = 2 
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 140 } 
		name = "I Région navale" 
		location = 43 
		base = 43 
		division = { 
			id = { type = 13500 id = 138 } 
			name = "11 Division de torpilleurs" 
			type = destroyer 
			model = 2
			} 
		division = { 
			id = { type = 13500 id = 168 } 
			name = "1 Division de transport" 
			type = transport 
			model = 1 
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 149 } 
		name = "II Région navale" 
		location = 37 
		base = 37
 		division = { 
			id = { type = 13500 id = 171 } 
			name = "2 Division de contre-torpilleurs" 
			type = destroyer 
			model = 4
			} 
		division = { 
			id = { type = 13500 id = 172 } 
			name = "2 Division de torpilleurs" 
			type = destroyer 
			model = 3
			} 
		division = { 
			id = { type = 13500 id = 173 } 
			name = "4 Division de torpilleurs" 
			type = destroyer 
			model = 3
			} 
		division = { 
			id = { type = 13500 id = 177 } 
			name = "6 Division de torpilleurs" 
			type = destroyer 
			model = 3
			} 
		division = { 
			id = { type = 13500 id = 178 } 
			name = "5 Division de torpilleurs" 
			type = destroyer 
			model = 2
			} 
		division = { 
			id = { type = 13500 id = 151 } 
			name = "2 Division de sous-marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 152 } 
			name = "6 Division de sous-marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 169 } 
			name = "2 Division de transport" 
			type = transport 
			model = 1 
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 155 } 
		name = "III Région navale" 
		location = 86 
		base = 86 
		division = { 
			id = { type = 13500 id = 139 } 
			name = "13 Division de torpilleurs" 
			type = destroyer 
			model = 2
			} 
		division = { 
			id = { type = 13500 id = 156 } 
			name = "1 Division de sous-marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 157 } 
			name = "3 Division de sous-marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 158 } 
			name = "13 Division de sous-marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 159 } 
			name = "7 Division de sous-marins" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 13500 id = 160 } 
			name = "19 Division de sous-marins" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 13500 id = 170 } 
			name = "3 Division de transport" 
			type = transport 
			model = 1 
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 161 } 
		name = "IV Région navale" 
		location = 748 
		base = 748 
		division = { 
			id = { type = 13500 id = 180 } 
			name = "1 Division de contre-torpilleurs" 
			type = destroyer 
			model = 4
			} 
		division = { 
			id = { type = 13500 id = 181 } 
			name = "8 Division de torpilleurs" 
			type = destroyer 
			model = 3
			} 
		division = { 
			id = { type = 13500 id = 185 } 
			name = "9 Division de torpilleurs" 
			type = destroyer 
			model = 2
			} 
		division = { 
			id = { type = 13500 id = 286 } 
			name = "12 Division de torpilleurs" 
			type = destroyer 
			model = 2
			strength = 40
			} 
		division = { 
			id = { type = 13500 id = 153 } 
			name = "4 Division de sous-marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 154 } 
			name = "12 Division de sous-marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 162 } 
			name = "14 Division de sous-marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 163 } 
			name = "17 Division de sous-marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 164 } 
			name = "18 Division de sous-marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 165 } 
			name = "9 Division de sous-marins" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 13500 id = 166 } 
			name = "10 Division de sous-marins" 
			type = submarine 
			model = 2 
			} 
		division = { 
			id = { type = 13500 id = 175 } 
			name = "4 Division de transport" 
			type = transport 
			model = 1 
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 167 } 
		name = "V Région navale" 
		location = 39 
		base = 40 
		division = { 
			id = { type = 13500 id = 187 } 
			name = "12 Division de torpilleurs" 
			type = destroyer 
			model = 2
			} 
		division = { 
			id = { type = 13500 id = 176 } 
			name = "5 Division de transport" 
			type = transport 
			model = 1 
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 174 } 
		name = "Forces navales d'Extrême-Orient" 
		location = 1392 
		base = 1395
 		division = { 
			id = { type = 13500 id = 134 } 
			name = "Suffren" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 126 } 
			name = "Primauguet" 
			type = light_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 3
			} 
		division = { 
			id = { type = 13500 id = 182 } 
			name = "6 Division de transport" 
			type = transport 
			model = 1 
			} 
		}      
	navalunit = { 
		id = { type = 13500 id = 179 } 
		name = "Station navale d'Afrique occidentale" 
		location = 978 
		base = 978 
		division = { 
			id = { type = 13500 id = 137 } 
			name = "Jeanne d'Arc" 
			type = light_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 3
			} 
		division = { 
			id = { type = 13500 id = 183 } 
			name = "7 Division de transport" 
			type = transport 
			model = 1 
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 184 } 
		name = "Station navale du Levant" 
		location = 1019 
		base = 1019 
		division = { 
			id = { type = 13500 id = 346 } 
			name = "11 Division de sous-marins" 
			type = submarine 
			model = 1 
			} 
		} 
	# ###############
	# French Airforce
	# ###############
   airunit = 
   {  id       = {  type = 13500 id = 188  } 
     name     = "1ère Division Aérienne" 
     location = 104 
     base     = 104 
     Division = 
     {  id       = {  type = 13500 id = 198  } 
       name     = "Groupement de Chasse 21" 
       strength = 80 
       type     = interceptor 
       model    = 7 
      } 
     Division = 
     {  id       = {  type = 13500 id = 200  } 
       name     = "Groupement de Chasse 23" 
       strength = 75 
       type     = interceptor 
	   model = 7
      } 
     Division = 
     {  id       = {  type = 13500 id = 189  } 
       name     = "Groupement de Chasse 25" 
       strength = 25 
       type     = interceptor 
	   model = 6
      } 
     Division = 
     {  id       = {  type = 13500 id = 190  } 
       name     = "Groupement de Bombardement 1" 
       strength = 90 
       type     = tactical_bomber 
	   model = 4
      } 
    } 
   airunit = 
   {  location = 55 
     base     = 55 
     id       = {  type = 13500 id = 192  } 
     name     = "2ème Division Aérienne" 
     Division = 
     {  id       = {  type = 13500 id = 293  } 
       name     = "Groupement de Chasse 22" 
       strength = 75 
       type     = interceptor 
	   model = 5
      } 
    } 
   airunit = 
   {  location = 54 
     base     = 54
     id       = {  type = 13500 id = 294  } 
     name     = "3ème Division Aérienne" 
     Division = 
     {  id       = {  type = 13500 id = 197  } 
       name     = "Groupement de Chasse 24" 
       strength = 100 
       type     = interceptor 
       model    = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 191  } 
       name     = "Groupement de Bombardement 3" 
       strength = 90 
       type     = tactical_bomber 
	   model = 4
      } 
    } 
   airunit = 
   {  location = 43 
     base     = 43 
     id       = {  type = 13500 id = 196  } 
     name     = "Aéronautique navale" 
     Division = 
     {  id       = {  type = 13500 id = 295  } 
       name     = "Flottille 5F" 
       strength = 45 
       type     = naval_bomber 
	   model = 1
      } 
    } 
 
   # ################################# 
   # Naval units under construction 
   # ################################# 
   division_development = 
   {  name  = "Dunkerque" 
     type  = battlecruiser 
     model = 3
	new_model = no
     cost  = 0.4 
	extra1 = floatplane
	brigade_model1 = 5
     id    = {  type = 13500 id = 300  } 
     date  = {  year = 1937 month = may day = 1  } 
    }
   division_development = 
   {  name  = "Algérie" 
     type  = heavy_cruiser 
     model = 4
	new_model = no
     cost  = 0.3 
	extra1 = floatplane
	brigade_model1 = 4
     id    = {  type = 13500 id = 301  } 
     date  = {  year = 1934 month = september day = 15  } 
    }
   division_development = 
   {  name  = "La Galissonière" 
     type  = light_cruiser 
     model = 4
	new_model = no
     cost  = 0.2 
	extra1 = floatplane
	brigade_model1 = 3
     id    = {  type = 13500 id = 302  } 
     date  = {  year = 1936 month = january day = 1  } 
    }
   division_development = 
   {  name  = "Émile Bertin" 
     type  = light_cruiser 
     model = 4
	new_model = no
     cost  = 0.2 
	extra1 = floatplane
	brigade_model1 = 3
     id    = {  type = 13500 id = 303  } 
     date  = {  year = 1935 month = january day = 28  } 
    }
   division_development = 
   {  name  = "Jean de Vienne" 
     type  = light_cruiser 
     model = 4
	new_model = no
     cost  = 0.2 
	extra1 = floatplane
	brigade_model1 = 3
     id    = {  type = 13500 id = 305  } 
     date  = {  year = 1937 month = february day = 10  } 
    }
   division_development = 
   {  name  = "10 Division de contre-torpilleurs" 
     type  = destroyer 
     model = 4
	new_model = no
     cost  = 0.1 
     id    = {  type = 13500 id = 306  } 
     date  = {  year = 1936 month = may day = 1  } 
    }
   division_development = 
   {  name  = "9 Division de contre-torpilleurs" 
     type  = destroyer 
     model = 4
	new_model = no
     cost  = 0.1 
     id    = {  type = 13500 id = 304  } 
     date  = {  year = 1934 month = april day = 1  } 
    }
   division_development = 
   {  name  = "5 Division de contre-torpilleurs" 
     type  = destroyer 
     model = 4
	new_model = no
     cost  = 0.1 
     id    = {  type = 13500 id = 310  } 
     date  = {  year = 1933 month = april day = 6  } 
    }
   division_development = 
   {  name  = "15 Division de sous-marins" 
     type  = submarine
     model = 3
	new_model = no
     cost  = 0.1 
     id    = {  type = 13500 id = 311  } 
     date  = {  year = 1934 month = may day = 1  } 
    }
   division_development = 
   {  name  = "16 Division de sous-marins" 
     type  = submarine 
     model = 3
	new_model = no
     cost  = 0.1 
     id    = {  type = 13500 id = 312  } 
     date  = {  year = 1933 month = may day = 18  } 
    }
	division_development = { 
		id = { type = 13500 id = 150 } 
		name = "Surcouf" 
		type = nuclear_submarine 
		model = 0 
		cost = 0.1
		date = { year = 1934 month = may day = 0 }
		extra1 = floatplane
		brigade_model1 = 4
	} 
	province_development = { 
		id = { type = 13500 id = 307 } 
		location = 107 
		cost = 0.1 
		size = 3
		type = land_fort 
		date  = {  year = 1964 } 
		} 
	province_development = { 
		id = { type = 13500 id = 308 } 
		location = 105 
		cost = 0.1 
		size = 3 
		type = land_fort 
		date  = {  year = 1964 } 
		} 		
	province_development = { 
		id = { type = 13500 id = 309 } 
		location = 104 
		cost = 0.1 
		size = 3 
		type = land_fort 
		date  = {  year = 1964 } 
		} 	

} 
 
