 # Ministres OK
 # OOB OK

 ############################## 
 # Country definition for GER # 
 ############################## 

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = GER 
    
   
	ai = "ger_1933.ai"
	ai_settings	= { flags = { GERBuildStandard = yes MOB1 = yes MOB2 = yes } }
	flag_ext = _weimar
	capital                = 163 
	manpower               = 34
	transports             = 580 
	escorts                = 23 
	dissent = 40
	# Resource Reserves 
	energy                 = 9000
	metal                  = 4500
	rare_materials         = 2250
	oil                    = 1000 
	supplies               = 500 
	money                  = 70 
   diplomacy = 
   {  relation = {  tag = ARG value = 75  } 
     relation = {  tag = AST value = 1  } 
     relation = 
     {  tag        = AUS 
       value      = 100 
       #guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = BEL value = 20  } 
     relation = {  tag = BHU value = 1  } 
     relation = {  tag = BOL value = 15  } 
     relation = {  tag = BRA value = 50  } 
     relation = 
     {  tag        = BUL 
       value      = 25 
       #guaranteed = {  day = 29 month = december year = 1932  }  
      } 
     relation = {  tag = CAN value = 1  } 
     relation = {  tag = CHL value = 50  } 
     relation = {  tag = COL value = -20  } 
     relation = 
     {  tag        = CZE 
       value      = -25 
       #guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = ENG value = 1  } 
     relation = 
     {  tag        = DEN 
       value      = 25 
       guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = EST value = 10  } 
     relation = 
     {  tag        = FIN 
       value      = 25 
       #guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = FRA value = -35  } 
     relation = {  tag = GRE value = 15  } 
     relation = {  tag = HOL value = 1  } 
     relation = {  tag = HUN value = 100  } 
     relation = {  tag = IRE value = 15  } 
     relation = {  tag = IRQ value = 25  } 
     relation = 
     {  tag        = ITA 
       value      = -50#50 
       guaranteed = {  day = 29 month = december year = 1932  }  
      } 
     relation = {  tag = JAP value = 20  } 
     relation = {  tag = LAT value = 10  } 
     relation = {  tag = LIT value = -50  } 
     relation = {  tag = LUX value = -50  } 
     relation = {  tag = MAN value = 20  } 
     relation = {  tag = NEP value = 1  } 
     relation = {  tag = NZL value = 1  } 
     relation = {  tag = OMN value = 1  } 
     relation = 
     {  tag        = POL 
       value      = -10 
       guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = POR value = 75  } 
     relation = 
     {  tag        = ROM 
       value      = 50 
       #guaranteed = {  day = 29 month = december year = 1932  }  
      } 
     relation = {  tag = SAF value = 1  } 
     relation = 
     {  tag        = SCH 
       value      = 50 
       guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = SOV value = 1  } 
     relation = {  tag = SPR value = -50  } 
     relation = 
     {  tag        = SWE 
       value      = 50 
       guaranteed = {  day = 29 month = december year = 1932  }  
      } 
     relation = 
     {  tag        = TUR 
       value      = 100 
       #guaranteed = {  day = 29 month = december year = 1932  }  
      } 
     relation = {  tag = USA value = -10  } 
     relation = {  tag = YEM value = 1  } 
     relation = 
     {  tag        = YUG 
       value      = 50 
       #guaranteed = {  day = 29 month = december year = 1932  } 
      } 
    } 
   SpyInfo                = {  country = "GER" NumberOfSpies = 7  } 
   
   nationalprovinces      = {  126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 216 221 224 225 261 389 392 
 # Austria 
 143 186 187 188 189 190 191 192 193 194 195 
 # Poland 
 # 226 230 222 # Granted by Ribbentrop-Molotov pact, allow 'Danzig or War?'
 401 402 # Trento Bolzano
                             } 
   ownedprovinces         = {  126  145  131  142  147  141  137  174  171  176  146  148  154  151  152  153 156 169 157 163 162 158 183 159 172 170 173 177 138 
                              134 132 178 175 179 167 164 184 133 128 130
         182 155 161 185 165 166 168 150 143 
         144 160 180 136 139 135 129 149 140 
                             } 
   controlledprovinces    = {  126  145  131  142  147  141  137  174  171  176  146  148  154  151  152  153 156 169 157 163 162 158 183 159 172 170 173 177 138 
                              134 132 178 175 179 167 164 184 133 128 130
         182 155 161 185 165 166 168 150 143 
         144 160 180 136 139 135 129 149 140 
                             } 
claimedprovinces = { # 846 847 848 849 850 851 882 883 884 885 886 908 909 910 911 919 925 928 933 936 948 950 955  # Afrika (Added in decision)
1234 1587 1602 1603 1605 1610 1665 1666 1667 1668 1669 1670 1671 1674 1675 1676 1677 1681 1684 1685 1686 1725 1726 1727 # Pacific
1731 #Apia
1328 # Qingdao
}
# Germany 1933 techs 
# ###################### 
	techapps = { 
	#Early Infantry Division  
	1010 1020 1030 1040 1050 1060 1070 1080 1090
	#SEMI-MOTORIZED CAVALRY 
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370
	#Early Mountain Division 
	1160  1170 1180 1190 1200 1210 1220 1230 1240
	#Engineers
	1830 1840 1850 1860
	#Interbellum 1930 Supply
	1910 1920 1930 1940 1950 1960 1970 1980

	#Basic Armoured Car  
	2860 2870 2880 2020
	#Early Tank 
	7600 7610 2620 2010 2630 2640 2646
	#Early Field Artillery 
	2290 2300 2310 2900 2910 2920 2930
	#Early Static Anti-Air Artillery 
	2800 2450 21180 21190
	#Basic Anti-Air Artillery Brigade 
	2810 2820 2510

	# Destroyer 
	3010 3020 3030 3040 3050
	# Light Cruiser 
	3110 3120 3130 3140 3150 
	# Heavy Cruiser 
	3210 3220 3230 3240 3250   
	# Battlecruiser
	3310 3320 3330 
	# Battleship 
	3410 3420 3430 3440 3450 3456 3460 
	# Submarine 
	3610 3620 3630 3640 3650
	# Light carrier 
	12100
	#Torpedo & ASW 18
	3720 3730 3736 3740 3750 3900
	#Troopships
	3810

	#Basic Air Transport 
	4290
	#Multirole fighter
	4300 4310 4320 4330 4340
	#ww1 strategic bomber
	4800 4810 4820
	#ww1 navalbomber
	4700 4710
	#Early Fighter  
	4500 4510 4520 4530 4540 4550 4010 4020
	#Early Bomber
	4600 4610 4620 4630 4120 4130
	#SEAPLANES
	4740 4750 4760

	#Manufacturing
	5810 5820 5050 5830 5060
	#Improved Construction Engineering 
	5800 5080 5090
	#Basic Oil Refining
	5190 #5200
	#Computers & cryptografi
	5310 54010 54020 54030 5316 5326
	#Exp. Rocket
	5560
	#Mechanized Agriculture 
	5700 5710 5010 5020
	#Medicine
	5600 5610 5620 #5630

	# Great War Land Doctrines (central powers)
	6500 6510 6530 6550 6590 6600 6620 6650 6670 6610 6680 6690 6700 6710 6910
	# WW2 Land Doctrines
	6210 #6220
	#Great War Hospital System 
	14000 14010 14020

	#Air Doctrines - ww2 techs
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 

	#Naval Doctrines
	8010 8020 8030 8040 8050 8060 8070 8080
	# Amphib
	82300
	# Naval Logistics
	82500
	# Naval Interdiction
	8500 8510 8520 8550 8560 8570
	# Trade Interdiction Submarine
	8600 8610
	# Indirect Approach
	81300 81310 81320 81330 81340 81350
	# Naval Supremacy
	8100 8110 8120 8150 8160 8170 8200 8210

	# CV 1922 (for gameplay purposes, to allow naval limitations to work as intended)
	3510
	#Carrier Pigeons
	30020 30030
} 
inventions = { 3000027 3000028 }
blueprints = { 7550 } # Rocket test and research facility (Removed land doc: Awarded with Guderian's Achtung Panzer event)
   policy = 
   {  date              = {  year = 1933 month = march day = 4  }  
     democratic        = 4 
     political_left    = 4 
     free_market       = 7 
     freedom           = 6 
     professional_army = 2 
     defense_lobby     = 4 # 5 (Hitler Speech to Heer will give +1) 
     interventionism   = 5 
    } 
	#peacetime_ic_mod       = 0.9 
	industrial_modifier			= 0.64 # (1.04 - 0.4) #This overwrites misc resource (metal etc) efficiency modifiers, as well as counts against IC
   headofstate            = {  type = 9 id = 268  } # Hindenburg
   headofgovernment       = {  type = 9 id = 269  } # Von Schleicher
   foreignminister        = {  type = 9 id = 47  } # Von Papen
   armamentminister       = {  type = 9 id = 207  } # Alfred Hugenberg (used to be Werner von Blomberg, who was Minister of War)
   ministerofsecurity     = {  type = 9 id = 101  } # Wilhelm von Gayl
   ministerofintelligence = {  type = 9 id = 279  } # Konrad Patzig
   chiefofstaff           = {  type = 9 id = 7  } # Ludwig Beck
   chiefofarmy            = {  type = 9 id = 8  } # Werner von Fritsch
   chiefofnavy            = {  type = 9 id = 9  } # Erich Raeder
   chiefofair             = {  type = 9 id = 10  } # Hermann Goering
   dormant_leaders        = {  36 44 54 66 67 223 226 292 352 473 479 526
							   542 543 544 546 547 549 550 551 553 558 559 560 561 562 563 
							   567 571 572 573 578 595 686 712 746 749 816 821 909 983 992
							   576 1007 1008 #Vlassov Zverev Budyho
							}
   dormant_ministers = { 37 189 65 } # Rosenberg and Frank come with Thule Society event, Speer comes with Rise of Speer
	### Naval limitations

	allowed_divisions = { 
		battleship = no
		light_cruiser = no
		heavy_cruiser = no
		battlecruiser = no
		destroyer = no
		carrier = no
		escort_carrier = no
		} 

   landunit = 
   {  location = 184 
     name     = "Wehrkreiskommando I" 
     id       = {  type = 14500 id = 34  } 
     Division = 
     {  id       = {  type = 14500 id = 35  } 
       name     = "1. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 75 
      } 
    } 
   landunit = 
   {  location = 158 
     name     = "Wehrkreiskommando II" 
     id       = {  type = 14500 id = 38  } 
     Division = 
     {  id       = {  type = 14500 id = 41  } 
       name     = "2. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 75 
      } 
    } 
   landunit = 
   {  location = 163 
     name     = "Wehrkreiskommando III" 
     id       = {  type = 14500 id = 42  } 

     Division = 
     {  id       = {  type = 14500 id = 43  } 
       name     = "3. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 75 
      } 
    } 
   landunit = 
   {  location = 163 
      leader   = 577 # Adam
     name     = "Gruppenkommando 1" 
     id       = {  type = 14500 id = 45  } 
     Division = 
     {  id       = {  type = 14500 id = 1706  } 
       name     = "Truppenamt des Reichsheeres" 
       type     = hq 
       model    = 2 
       strength = 75 
      } 
     Division = 
     {  id       = {  type = 14500 id = 46  } 
       name     = "1. Kavallerie-Division" 
       type     = cavalry
       model    = 9 
       strength = 75 
      } 
     Division = 
     {  id       = {  type = 14500 id = 47  } 
       name     = "2. Kavallerie-Division" 
       type     = cavalry
       model    = 9
       strength = 75 
      } 
    } 
   landunit = 
   {  location = 134 
     name     = "Wehrkreiskommando V" 
     id       = {  type = 14500 id = 49  } 
     Division = 
     {  id            = {  type = 14500 id = 51  } 
       name          = "5. Infanterie-Division" 
       type          = infantry 
       model         = 8
       strength      = 75 
      } 
    } 
   landunit = 
   {  location = 141 
     name     = "Wehrkreiskommando VI" 
     id       = {  type = 14500 id = 53  } 
     Division = 
     {  id       = {  type = 14500 id = 54  } 
       name     = "6. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 75 
      } 
    } 
   landunit = 
   {  location = 137 
     name     = "Gruppenkommando 2" 
     id       = {  type = 14500 id = 57  } 
     Division = 
     {  id       = {  type = 14500 id = 58  } 
       name     = "3. Kavallerie-Division" 
       type     = cavalry
       model    = 9 
       strength = 75 
      } 
    } 
   landunit = 
   {  location = 173 
     name     = "Wehrkreiskommando IV" 
     id       = {  type = 14500 id = 65  } 
     Division = 
     {  id       = {  type = 14500 id = 66  } 
       name     = "4. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 75 
      } 
    } 
   landunit = 
   {  location = 179 
     name     = "Wehrkreiskommando VII" 
     id       = {  type = 14500 id = 69  } 
     Division = 
     {  id       = {  type = 14500 id = 71  } 
       name     = "7. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 75 
      } 
    } 



   navalunit = 
   {  name     = "Reichsmarine" 
     id       = {  type = 14500 id = 1  } 
     location = 147 
     base     = 147 
     Division = 
     {  id    = {  type = 14500 id = 2  } 
       name  = "Schlesien" 
       type  = battleship 
       model = 1
	extra1 = naval_anti_air_l
	brigade_model1 = 0
      } 
     Division = 
     {  id    = {  type = 14500 id = 3  } 
       name  = "Schleswig-Holstein" 
       type  = battleship 
       model = 1
	extra1 = naval_anti_air_l
	brigade_model1 = 0
      } 
     Division = 
     {  id    = {  type = 14500 id = 11  } 
       name  = "Hessen" 
       type  = battleship 
       model = 1
      } 
     Division = 
     {  id    = {  type = 14500 id = 5  } 
       name  = "Leipzig" 
       type  = light_cruiser 
       model = 3 
	extra1 = floatplane
	brigade_model1 = 3
      } 
     Division = 
     {  id    = {  type = 14500 id = 6  } 
       name  = "Königsberg" 
       type  = light_cruiser 
       model = 3 
	extra1 = floatplane
	brigade_model1 = 3
      } 
     Division = 
     {  id    = {  type = 14500 id = 7  } 
       name  = "Karlsruhe" 
       type  = light_cruiser 
       model = 3 
	extra1 = floatplane
	brigade_model1 = 3
      } 
     Division = 
     {  id    = {  type = 14500 id = 8  } 
       name  = "Köln" 
       type  = light_cruiser 
       model = 3 
	extra1 = floatplane
	brigade_model1 = 3
      } 
     Division = 
     {  id    = {  type = 14500 id = 9  } 
       name  = "Emden" 
       type  = light_cruiser 
       model = 2 
      } 
     Division = 
     {  id    = {  type = 14500 id = 4  } 
       name  = "Berlin" 
       type  = light_cruiser 
       model = 1 
      } 
     Division = 
     {  id    = {  type = 14500 id = 12  } 
       name  = "1. Torpedobootsflottille" 
       type  = destroyer 
       model = 1 
      } 
     Division = 
     {  id    = {  type = 14500 id = 13  } 
       name  = "2. Torpedobootsflottille" 
       type  = destroyer 
       model = 2 
      } 
     Division = 
     {  id    = {  type = 14500 id = 14  } 
       name  = "3. Torpedobootsflottille" 
       type  = destroyer 
       model = 2 
      } 
     Division = 
     {  id    = {  type = 14500 id = 15  } 
       name  = "4. Torpedobootsflottille" 
       type  = destroyer 
       model = 3 
	strength = 80
      } 
     Division = 
     {  id    = {  type = 14500 id = 16  } 
       name  = "5. Torpedobootsflottille" 
       type  = destroyer 
       model = 3 
	strength = 80
      } 
     Division = 
     {  id    = {  type = 14500 id = 17  } 
       name  = "6. Torpedobootsflottille" 
       type  = destroyer 
       model = 3 
	strength = 80
      } 
     Division = 
     {  id    = {  type = 14500 id = 105  } 
       name  = "1. Truppentransporterflottille" 
       type = transport
	model = 1 
      } 
     Division = 
     {  id    = {  type = 14500 id = 106  } 
       name  = "2. Truppentransporterflottille" 
       type = transport 
	model = 1 
      } 
     Division = 
     {  id    = {  type = 14500 id = 107  } 
       name  = "3. Truppentransporterflottille" 
       type = transport 
	model = 1 
      } 
    }
   # ######### Luftwaffe ############## 
   airunit = 
   {  location = 163 
     id       = {  type = 14500 id = 86  } 
     name     = "Kampffliegerschule" 
     base     = 163 
     Division = 
     {  id            = {  type = 14500 id = 90  } 
       name          = "Kampffliegerschule" 
       strength      = 50 
       type          = interceptor 
       model         = 6
      } 
    } 
   airunit = 
   {  location = 163 
     id       = {  type = 14500 id = 95  } 
     name     = "Deutsche Luft Hansa" 
     base     = 163 
     Division = 
     {  id       = {  type = 14500 id = 96  } 
       name     = "Blitzstrecken" 
       strength = 60 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 97  } 
       name     = "Luft Hansa" 
       strength = 100 
       type     = transport_plane 
       model    = 0
      } 
    } 

	# ####under developement##### 
	division_development = {
		name  = "Admiral Graf Spee" 
		type  = heavy_cruiser
		model = 4
	new_model = no
		cost  = 0.3 
		id    = {  type = 14500 id = 500  } 
		date  = {  year = 1936 month = january day = 6  } 
	extra1 = floatplane
	brigade_model1 = 4
	extra2 = naval_fire_controll_s
	brigade_model2 = 0
	extra3 = naval_improved_hull_s
	brigade_model3 = 0
	} 
	division_development = {
		name  = "Admiral Scheer" 
		type  = heavy_cruiser
		model = 4
	new_model = no
		cost  = 0.3 
		id    = {  type = 14500 id = 501  } 
		date  = {  year = 1934 month = november day = 12  } 
	extra1 = floatplane
	brigade_model1 = 4
	extra2 = naval_fire_controll_s
	brigade_model2 = 0
	extra3 = naval_improved_hull_s
	brigade_model3 = 0
	} 
	division_development = {
		name  = "Deutschland" 
		type  = heavy_cruiser
		model = 4
	new_model = no
		cost  = 0.3 
		id    = {  type = 14500 id = 502  } 
		date  = {  year = 1933 month = april day = 1  } 
	extra1 = floatplane
	brigade_model1 = 4
	extra2 = naval_fire_controll_s
	brigade_model2 = 0
	extra3 = naval_improved_hull_s
	brigade_model3 = 0
	} 
	division_development = {
		name  = "Nürnberg" 
		type  = light_cruiser
		model = 4
	new_model = no
		cost  = 0.2 
		id    = {  type = 14500 id = 503  } 
		date  = {  year = 1935 month = november day = 1  } 
	extra1 = floatplane
	brigade_model1 = 3
	}

# Wehrmacht 1935

     landdivision = 
     { dormant = yes
       id       = {  type = 14500 id = 1001  } 
       name     = "61. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1002  } 
       name     = "206. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1003  } 
       name     = "217. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1004  } 
       name     = "228. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 39  } 
       name     = "75. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 40  } 
       name     = "207. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1005  } 
       name     = "258. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1006  } 
       name     = "50. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1007  } 
       name     = "68. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1008  } 
       name     = "76. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1009  } 
       name     = "208. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1010  } 
       name     = "218. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1011  } 
       name     = "257. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1012  } 
       name     = "93. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 48  } 
       name     = "62. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1013  } 
       name     = "213. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1014  } 
       name     = "221. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1015  } 
       name     = "252. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 50  } 
       name     = "78. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 52  } 
       name     = "260. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 56  } 
       name     = "69. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1016  } 
       name     = "86. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1017  } 
       name     = "211. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1018  } 
       name     = "227. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1019  } 
       name     = "253. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1020  } 
       name     = "254. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 60  } 
       name     = "52. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1021  } 
       name     = "214. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1022  } 
       name     = "239. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1023  } 
       name     = "251. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1024  } 
       name     = "95. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 62  } 
       name     = "79. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 63  } 
       name     = "246. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 64  } 
       name     = "262. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1025  } 
       name     = "263. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1026  } 
       name     = "56. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1027  } 
       name     = "87. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1028  } 
       name     = "209. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1029  } 
       name     = "223. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1030  } 
       name     = "255. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1031  } 
       name     = "256. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1032  } 
       name     = "94. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 70  } 
       name     = "57. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 72  } 
       name     = "212. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 73  } 
       name     = "67. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 75  } 
       name     = "58. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 77  } 
       name     = "70. Infanterie-Division" 
       type     = infantry 
       model    = 7 
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1033  } 
       name     = "215. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1034  } 
       name     = "225. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1035  } 
       name     = "269. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 79  } 
       name     = "71. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 81  } 
       name     = "216. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1036  } 
       name     = "267. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1037  } 
       name     = "96. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1041  } 
       name     = "73. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1042  } 
       name     = "231. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1043  } 
       name     = "98. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1044  } 
       name     = "22. Infanterie-Division" 
       type     = infantry 
       model    = 5
       strength = 5 
      } 

###Special Units

      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1045  } 
       name     = "22. (LL.) Infanterie-Division" 
       type     = paratrooper 
       model    = 0
       experience = 40
      } 
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1046  } 
       name     = "1. SS-Inf.Div. Leibstandarte Adolf Hitler" 
       type     = d_01
       model    = 0
       experience = 100
       strength = 30
       max_strength = 30
      } 
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1047  } 
       name     = "1.SS-Pz.Div. LSSAH" 
       type     = d_04
       model    = 0
       experience = 100
      } 
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1048  } 
       name     = "3. SS-Inf.Div. Totenkopf" 
       type     = d_02
       model    = 1
       experience = 80
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1049  } 
       name     = "3. SS-Pz.Div. 'Totenkopf'" 
       type     = d_04
       model    = 1
       experience = 80
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1050  } 
       name     = "2. SS-Div. Verfügungstruppe" 
       type     = d_01
       model    = 0
       experience = 80
       strength = 60
       max_strength = 30
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1051  } 
       name     = "2. SS-Inf.Div. „Reich“ (mot.) " 
       type     = d_02
       model    = 0
       experience = 80
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1052  } 
       name     = "2. SS-Pz.Div. 'Das Reich'" 
       type     = d_04
       model    = 1
       experience = 80
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1053  } 
       name     = "2. SS-Inf.Div. 'Polizei-Division'" 
       type     = d_01
       model    = 1
       extra = police
       brigade_model = 1
       experience = 50
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1054  } 
       name     = "4. SS-Polizei-Panzergrenadier-Division" 
       type     = d_03
       model    = 0
       extra = police
       brigade_model = 1
       experience = 50
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1055  } 
       name     = "5. SS-Inf.Div. 'Wiking'" 
       type     = d_01
       model    = 1
       experience = 40
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1056  } 
       name     = "5. SS-Pz.Div. 'Wiking'" 
       type     = d_04
       model    = 1
       experience = 40
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1057  } 
       name     = "6. SS-Gebirgs-Div. 'Nord'" 
       type     = d_01
       model    = 2
       experience = 30
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1058  } 
       name     = "7. SS-Freiwilligen-Gebirgs-Div. 'Prinz Eugen'" 
       type     = d_01
       model    = 1
       experience = 20
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1059  } 
       name     = "8. SS-Kavallerie-Div. 'Florian Geyer'" 
       type     = d_01
       model    = 2
       extra = cavalry_brigade
       brigade_model = 11
       experience = 20
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1060  } 
       name     = "9. SS-Pz.Div. 'Hohenstaufen'" 
       type     = d_04
       model    = 1
       experience = 80
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1061  } 
       name     = "10. SS-Pz.Div. 'Frundsberg'" 
       type     = d_04
       model    = 1
       experience = 80
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1062  } 
       name     = "11. SS-Freiwilligen-Panzergrenadier-Div. 'Nordland'" 
       type     = d_03
       model    = 0
       experience = 20
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1063  } 
       name     = "12. SS-Inf.Pz. 'Hitlerjugend'" 
       type     = d_04
       model    = 1
       experience = 80
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1064  } 
       name     = "Infanterie-Div. 'Großdeutschland' (mot.)" 
       type     = motorized
       model    = 1
       experience = 100
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1065  } 
       name     = "Panzergrenadier-Div. 'Großdeutschland'" 
       type     = mechanized
       model    = 0
       experience = 100
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1066  } 
       name     = "Panzer-Lehr-Div." 
       type     = armor
       model    = 3
       extra = super_heavy_armor
       brigade_model = 1
       experience = 100
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1067  } 
       name     = "7. Fliegerdivision" 
       type     = paratrooper 
       model    = 0
       extra = glider_artillery
       brigade_model = 0
       experience = 100
      } 
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1068  } 
       name     = "13. Waffen-Gebirgs-Div. der SS 'Handschar'" 
       type     = d_08
       model    = 1
      } 
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1069  } 
       name     = "14. Waffen-Grenadier-Div. der SS (galizische Nr. 1)" 
       type     = d_08
       model    = 1
      } 
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1070  } 
       name     = "15. Waffen-Grenadier-Div. der SS (lettische Nr. 1)" 
       type     = d_08
       model    = 1
      } 
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1071  } 
       name     = "16. SS-Panzergrenadier-Div. 'Reichsführer SS'" 
       type     = d_03
       model    = 0
      } 
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1072  } 
       name     = "17. SS-Panzergrenadier-Div. 'Götz von Berlichingen'" 
       type     = d_03
       model    = 0
      } 
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1073  } 
       name     = "18. SS-Freiwilligen-Panzergrenadier-Div. 'Horst Wessel'" 
       type     = d_03
       model    = 0
      } 
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1074  } 
       name     = "19. Waffen-Grenadier-Div. der SS (lettische Nr. 2)" 
       type     = d_08
       model    = 1
      }
      airdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1075  } 
       name     = "Legion Condor" 
       type     = tactical_bomber 
       model    = 5
       experience = 80
      }
     airdivision = 
     { dormant = yes id       = {  type = 14500 id = 1076  } 
       name     = "JV 44 'Der Galland-Zirkus'" 
       strength = 100 
       type     = interceptor
       model    = 11
       experience = 100
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1077  } 
       name     = "2. Infanterie-Division (Mot)" 
       type     = motorized
       model    = 1
       experience = 20
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1078  } 
       name     = "61. Infanterie-Division (Mot)" 
       type     = motorized
       model    = 1
       experience = 20
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1079  } 
       name     = "206. Infanterie-Division (Mot)" 
       type     = motorized
       model    = 1
       experience = 20
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 1080  } 
       name     = "Hitler and Staff" 
       type     = d_10
       model    = 0
       experience = 100
	locked = yes
      }

landdivision = { dormant = yes id = { type = 14500 id = 2027 }  name = "1. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2028 }  name = "2. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2029 }  name = "3. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2030 }  name = "4. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2031 }  name = "5. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2032 }  name = "6. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2033 }  name = "7. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2034 }  name = "8. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2035 }  name = "9. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2036 }  name = "10. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2037 }  name = "11. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2038 }  name = "12. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2039 }  name = "13. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2040 }  name = "14. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2041 }  name = "15. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2042 }  name = "16. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2043 }  name = "17. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2044 }  name = "18. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2045 }  name = "19. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 14500 id = 2046 }  name = "2. Gebirgsjäger-Division"  type = bergsjaeger model = 10 extra = artillery brigade_model = 9 }
landdivision = { dormant = yes id = { type = 14500 id = 2047 }  name = "3. Gebirgsjäger-Division"  type = bergsjaeger model = 10 extra = artillery brigade_model = 9 }
landdivision = { dormant = yes id = { type = 14500 id = 2048 }  name = "169. Infanterie-Division"  type = infantry model = 10 extra = medium_armor brigade_model = 3 }  # Panzer-Abteilung 211/40th Panzer Battalion
landdivision = { dormant = yes id = { type = 14500 id = 2049 }  name = "SS-Division Nord"  type = motorized model = 1 }
landdivision = { dormant = yes id = { type = 14500 id = 2100 }  name = "20. Festung Europa"  type = garrison model = 5 extra = anti_air brigade_model = 9 locked  = yes } # Netherlands
landdivision = { dormant = yes id = { type = 14500 id = 2101 }  name = "21. Festung Europa"  type = garrison model = 5 extra = anti_air brigade_model = 9 locked  = yes } # Netherlands
landdivision = { dormant = yes id = { type = 14500 id = 2102 }  name = "22. Festung Europa"  type = garrison model = 5 extra = anti_air brigade_model = 9 locked  = yes } # Belgium
landdivision = { dormant = yes id = { type = 14500 id = 2103 }  name = "23. Festung Europa"  type = garrison model = 5 extra = anti_air brigade_model = 9 locked  = yes } # Belgium
landdivision = { dormant = yes id = { type = 14500 id = 2104 }  name = "24. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes } # Croatia
landdivision = { dormant = yes id = { type = 14500 id = 2105 }  name = "25. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes } # Greece
landdivision = { dormant = yes id = { type = 14500 id = 2106 }  name = "26. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes } # Denmark
landdivision = { dormant = yes id = { type = 14500 id = 2107 }  name = "27. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes } # Norway
landdivision = { dormant = yes id = { type = 14500 id = 2108 }  name = "28. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes } # Norway
landdivision = { dormant = yes id = { type = 14500 id = 2109 }  name = "29. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes } # Norway
landdivision = { dormant = yes id = { type = 14500 id = 2110 }  name = "30. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes } # Norway
landdivision = { dormant = yes id = { type = 14500 id = 2111 }  name = "31. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes } # Norway
landdivision = { dormant = yes id = { type = 14500 id = 2112 }  name = "32. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes } # Norway
landdivision = { dormant = yes id = { type = 14500 id = 2113 }  name = "33. Festung Europa"  type = garrison model = 5 extra = anti_air brigade_model = 9 locked  = yes } # Belgium
landdivision = { dormant = yes id = { type = 14500 id = 2114 }  name = "34. Festung Europa"  type = garrison model = 5 extra = anti_air brigade_model = 9 locked  = yes } # Belgium

#foreign wehrmacht units

      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 2050  } 
       name     = "Turkistanische Legion"
       strength = 10
       type     = militia
       model    = 4
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 2051  } 
       name     = "369. (Kroatische) Infanterie-Division"
       strength = 65
       max_strength = 65
       type     = infantry
       model    = 9
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 2052  } 
       name     = "373. (Kroatische) Infanterie-Division"
       strength = 100
       type     = infantry
       model    = 9
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 2053  } 
       name     = "392. (Kroatische) Infanterie-Division"
       strength = 100
       type     = infantry
       model    = 9
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 2054  } 
       name     = "Armenische Legion"
       strength = 100
       type     = militia
       model    = 4
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 2055  } 
       name     = "Aserbaidschanische Legion"
       strength = 100
       type     = militia
       model    = 4
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 2056  } 
       name     = "Freikorps Dänemark"
       strength = 40
       max_strength = 40
       type     = infantry
       model    = 9
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 2057  } 
       name     = "Kalmücken-Kavallerie-Korps"
       strength = 55
       max_strength = 55
       type     = cavalry
       model    = 9
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 2058  } 
       name     = "Georgische Legion"
       strength = 100
       type     = militia
       model    = 4
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 2059  } 
       name     = "1. Kosaken-Division"
       strength = 55
       max_strength = 55
       type     = cavalry
       model    = 9
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 2060  } 
       name     = "Legion of French Volunteers Against Bolshevism"
       strength = 20
       max_strength = 50
       type     = infantry
       model    = 9
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 2061  } 
       name     = "Russisches Schutzkorps Serbien"
       strength = 100
       type     = militia
       model    = 4
      }
      landdivision = 
     { dormant = yes  id       = {  type = 14500 id = 2062  } 
       name     = "Russische Befreiungsarmee"
       strength = 100
       type     = militia
       model    = 4
      }
} 
