country = {
	tag			= U05
	puppet		= HOL
	control		= HOL	
	ai			= "U05_1936.ai"
	ai_settings	= { flags = { MOB1 = yes MOB2 = yes MOB3 = yes MOB4 = yes} }
	
	dissent = 20
	capital = 1647
	manpower = 83

	# Resource Reserves
	energy	=	1000   
	metal	= 1000		
	rare_materials =	500	
	oil =	500	
	supplies =	500
	money	=	40

   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 9 
     political_left    = 2 
     free_market       = 9 
     freedom           = 10 
     professional_army = 4 
     defense_lobby     = 1 
     interventionism   = 1 
    }
	headofstate            = {  type = 9 id = 840001  }
	headofgovernment       = {  type = 9 id = 840002  }
	foreignminister        = {  type = 9 id = 840003  }
	armamentminister       = {  type = 9 id = 840004  }
	ministerofsecurity     = {  type = 9 id = 840005  }
	ministerofintelligence = {  type = 9 id = 840006  }
	chiefofstaff           = {  type = 9 id = 840007  }
	chiefofarmy            = {  type = 9 id = 840008  }
	chiefofnavy            = {  type = 9 id = 840009  }
	chiefofair             = {  type = 9 id = 840051  } #Gustav Adolf Ilgen
	
	transports = 160
	escorts = 21
	
    ownedprovinces =      
{
	### Sumatra
	1639 #Bangka=>Bangka Island 
	1642 #Medan
	1640 #Koeta-Radja=>Medan(split)
	1635 #Djambi=>Dumai
	1634 #Pakan Baharoe=>Dumai(split) 
	1637 #Padang 
	1636 #Palembang 
	1641 #Oosthaven
	1638 #Bengkulu=>Oosthaven(split) 	

	### Java
	1647 #Batavia
	1648 #Tjilegon
	1646 #Tjilatjap
	1651 #Bandoeng=>Tjilatjap(split)
	1650 #Semarang
	1649 #Tjirebon=>Semarang
	1654 #Jogjakarta 
	1653 #Soerabaja
	1652 #Rembang=>Soerabaja(split) 
	1655 #Malang 
	1656 #Madura 

	### Flores
	1643 #Bali
	1645 #Waingapoe=>Sumba
	1615 #Flores
	1616 #Koepang=>West Timor
	1619 #Yamdena=>Flores(split)
	1644 #Sumbawa

	### Molukken
	1657 #Makassar 
	1658 #Kendari
	1660 #Paloe 
	1659 #Manado=>Menado
	1620 #Halmahera
	1621 #Buru
	1622 #Ceram

	### Neu Guinea
	1599 #Manoekwari=>Sorong
	1600 #Fak-Fak=>Babo
	1595 #Ansoes=>Arare
	1601 #Wakia=>Kokonau
	1618 #Aru=>Biak Islands
	1598 #Birab=>Agats
	1597 #Merauke
	1596 #Hollandia
	1594 #Wamena=>Sarmi

	### Borneo
	1633 #Bandjarmasin 
	1631 #Poentianak
	1628 #Bakon=>Semitau 
	1623 #Longmerah=>Mahakam 
	1627 #Tarakan/Samarinda
	1632 #Balikpapan 
	1629 #Singkawang=>Poentianak(split)
	1630 #Sampit=>Poentianak(split)

}
    controlledprovinces = 
{
	### Sumatra
	1639 #Bangka=>Bangka Island 
	1642 #Medan
	1640 #Koeta-Radja=>Medan(split)
	1635 #Djambi=>Dumai
	1634 #Pakan Baharoe=>Dumai(split) 
	1637 #Padang 
	1636 #Palembang 
	1641 #Oosthaven
	1638 #Bengkulu=>Oosthaven(split) 	

	### Java
	1647 #Batavia
	1648 #Tjilegon
	1646 #Tjilatjap
	1651 #Bandoeng=>Tjilatjap(split)
	1650 #Semarang
	1649 #Tjirebon=>Semarang
	1654 #Jogjakarta 
	1653 #Soerabaja
	1652 #Rembang=>Soerabaja(split) 
	1655 #Malang 
	1656 #Madura 

	### Flores
	1643 #Bali
	1645 #Waingapoe=>Sumba
	1615 #Flores
	1616 #Koepang=>West Timor
	1619 #Yamdena=>Flores(split)
	1644 #Sumbawa

	### Molukken
	1657 #Makassar 
	1658 #Kendari
	1660 #Paloe 
	1659 #Manado=>Menado
	1620 #Halmahera
	1621 #Buru
	1622 #Ceram

	### Neu Guinea
	1599 #Manoekwari=>Sorong
	1600 #Fak-Fak=>Babo
	1595 #Ansoes=>Arare
	1601 #Wakia=>Kokonau
	1618 #Aru=>Biak Islands
	1598 #Birab=>Agats
	1597 #Merauke
	1596 #Hollandia
	1594 #Wamena=>Sarmi

	### Borneo
	1633 #Bandjarmasin 
	1631 #Poentianak
	1628 #Bakon=>Semitau 
	1623 #Longmerah=>Mahakam 
	1627 #Tarakan/Samarinda
	1632 #Balikpapan 
	1629 #Singkawang=>Poentianak(split)
	1630 #Sampit=>Poentianak(split)
}
    nationalprovinces =   
{
	### Sumatra
	1639 #Bangka=>Bangka Island 
	1642 #Medan
	1640 #Koeta-Radja=>Medan(split)
	1635 #Djambi=>Dumai
	1634 #Pakan Baharoe=>Dumai(split) 
	1637 #Padang 
	1636 #Palembang 
	1641 #Oosthaven
	1638 #Bengkulu=>Oosthaven(split) 	

	### Java
	1647 #Batavia
	1648 #Tjilegon
	1646 #Tjilatjap
	1651 #Bandoeng=>Tjilatjap(split)
	1650 #Semarang
	1649 #Tjirebon=>Semarang
	1654 #Jogjakarta 
	1653 #Soerabaja
	1652 #Rembang=>Soerabaja(split) 
	1655 #Malang 
	1656 #Madura 

	### Flores
	1643 #Bali
	1645 #Waingapoe=>Sumba
	1615 #Flores
	1616 #Koepang=>West Timor
	1619 #Yamdena=>Flores(split)
	1644 #Sumbawa

	### Molukken
	1657 #Makassar 
	1658 #Kendari
	1660 #Paloe 
	1659 #Manado=>Menado
	1620 #Halmahera
	1621 #Buru
	1622 #Ceram

	### Neu Guinea
	1599 #Manoekwari=>Sorong
	1600 #Fak-Fak=>Babo
	1595 #Ansoes=>Arare
	1601 #Wakia=>Kokonau
	1618 #Aru=>Biak Islands
	1598 #Birab=>Agats
	1597 #Merauke
	1596 #Hollandia
	1594 #Wamena=>Sarmi

	### Borneo
	1633 #Bandjarmasin 
	1631 #Poentianak
	1628 #Bakon=>Semitau 
	1623 #Longmerah=>Mahakam 
	1627 #Tarakan/Samarinda
	1632 #Balikpapan 
	1629 #Singkawang=>Poentianak(split)
	1630 #Sampit=>Poentianak(split)
}

diplomacy = {
relation = { tag = HOL value = 150 }
relation = { tag = BEL value = 150 }
relation = { tag = CAN value = 80 }
relation = { tag = DEN value = 100 }
relation = { tag = ENG value = 125 }
relation = { tag = FIN value = 100 }
relation = { tag = FRA value = 75 }
relation = { tag = GER value = 0 }
relation = { tag = IRE value = 75 }
relation = { tag = ITA value = -20 }
relation = { tag = JAP value = -50 }
relation = { tag = LUX value = 150 }
relation = { tag = MEX value = 25 }
relation = { tag = NOR value = 100 }
relation = { tag = SWE value = 100 }
relation = { tag = USA value = 70 }
}
  SpyInfo                = { country = "U05" NumberOfSpies = 4 }


   techapps               = { 

#Naval Infantry
#1560 1570 1580
#Engineers
1830 1840 1850 1860
#Great War Infantry Division  
1010  1020 1030 1040 1050 1060 
#Interbellum 1930 Supply 
1910 1920 1930 1940 1950 1960 1970 1980
#Great War Cavalry Division  
13060 13070 13080 1310 1320 1330 1340 
#Early Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240
#Basic Armoured Car  
2860 2870 2880 2020
#Great War Heavy Field Artillery 
2290 2300 2310 
#Early Static Anti-Air Artillery
2800 2450 21180 21190
#Basic Anti-Air Artillery Brigade 
2810 2820 2510
#Light armor brigades only techs / advanced Light armor
7600 7610 2010 2630 2640
#Improved Destroyer 
3010 3020 3030 3040 3050 3060
#Interwar Light Cruiser 
3110 3120 3130 3140
#Improved Heavy Cruiser 
3210 3220 3230 3240 3250
#Interwar Battlecruiser 
3310 3320 3330 3340
#Great War Battleship 
3410 3420 3430 3440 3450 3456 3460
#Med Range Submarine 
3610 3620 3630 3640
#Torpedo & ASW 18
3720 3730 3736 3740 3900
#Troopships
3810
#Early Fighter  
4500 4510 4520 4530 4540 4550 4010 4020
#Interwar Bomber 
4600 4610 4620 4630 4120
#Multirole fighter
4300 4310 4320 4330
#ww1 strategic bomber
4800 4810 4820
#ww1 navalbomber
4700 4710
#Modern Agriculture 
5700 5710 5010
#Computers & cryptografi
5310 54010 54020 54030 5316 5326
#Manufactoring
5810 5820 5050 5830 5060
#Improved Construction Engineering 
5800 5080 5090 
#Faculty of Atomic Research 
5470
#Medicine
5600 5610 5620 5630
# Great War Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910
# Defensive Focus Grand Battleplan Path
6560 6030 6110
#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010
# Engagement Theories
8010 8020 8040 8050 8060 8070 8080
# Naval Supremacy
8100 8110 8120 8150 8160 8200 8210
# Naval Interdiction
8500 8510 8520 8600 8610
# Engagement Tactics
8900 8910 8920 8930 8940
#Great War Hospital System 
14000 14010 14020
} 
inventions = { 3000027 }

   landunit = 
   {  id       = {  type = 10100 id = 1  } 
     location = 1647 
     name     = "Koninklijk Nederlands Indisch Leger" 
     Division = 
     {  id   = {  type = 10100 id = 2  } 
       name = "Ie Divisie" 
	   strength     = 90
       type = infantry 
	   model = 6 
      } 
     Division = 
     {  id   = {  type = 10100 id = 3  } 
       name = "IIe Divisie" 
	   strength     = 60
       type = infantry
		model = 6 	   
      } 
    } 
   landunit = 
   {  id       = {  type = 10100 id = 4  } 
     location = 1653 
     name     = "Veiligheitsbezetting Soerabaja" 
     Division = 
     {  id   = {  type = 10100 id = 5  } 
       name = "IIIe Divisie" 
	   strength     = 100
       type = infantry 
	   model = 6 
      } 
    } 
   landunit = 
   {  id       = {  type = 10100 id = 6  } 
     location = 1642 
     name     = "Territoriaal Commando Noord-Sumatra" 
     Division = 
     {  id   = {  type = 10100 id = 7  } 
       name = "TC Noord-Sumatra" 
	   strength     = 20
       type = militia
	   model = 3 
      } 
    } 
   landunit = 
   {  id       = {  type = 10100 id = 8  } 
     location = 1637 
     name     = "Territoriaal Commando Sumatra's Westkust en Tapanoeli" 
     Division = 
     {  id   = {  type = 10100 id = 9  } 
       name = "TC Westkust-Sumatra" 
	   strength     = 15
       type = militia
	   model = 3 
      } 
    } 
   landunit = 
   {  id       = {  type = 10100 id = 10  } 
     location = 1635 
     name     = "Territoriaal Commando Riouw en Onderhorigheden" 
     Division = 
     {  id   = {  type = 10100 id = 11  } 
       name = "TC Riouw" 
	   strength     = 10
       type = militia
	   model = 3 
      } 
    } 
   landunit = 
   {  id       = {  type = 10100 id = 12  } 
     location = 1636
     name     = "Territoriaal Commando Zuid-Sumatra" 
     Division = 
     {  id   = {  type = 10100 id = 13  } 
       name = "TC Zuid-Sumatra" 
	   strength     = 10
       type = militia
	   model = 3 
      } 
    } 
   landunit = 
   {  id       = {  type = 10100 id = 14  } 
     location = 1631
     name     = "Territoriaal Commando Westerafdeling van Borneo" 
     Division = 
     {  id   = {  type = 10100 id = 15  } 
       name = "TC West-Borneo" 
	   strength     = 10
       type = militia
	   model = 3 
      } 
    } 
   landunit = 
   {  id       = {  type = 10100 id = 16  } 
     location = 1633 
     name     = "Territoriaal Commando Zuiden en Oosterafdeling van Borneo" 
     Division = 
     {  id   = {  type = 10100 id = 17  } 
       name = "TC Zuid-Oost-Borneo" 
	   strength     = 25
       type = militia
	   model = 3 
      } 
    } 
   landunit = 
   {  id       = {  type = 10100 id = 18  } 
     location = 1657 
     name     = "Territoriaal Commando Celebes en Manado" 
     Division = 
     {  id   = {  type = 10100 id = 19  } 
       name = "TC Celebes" 
	   strength     = 15
       type = militia
	   model = 3 
      } 
    } 
   landunit = 
   {  id       = {  type = 10100 id = 20  } 
     location = 1616 
     name     = "Territoriaal Commando Timor en Onderhorigheden" 
     Division = 
     {  id   = {  type = 10100 id = 21  } 
       name = "TC Timor" 
	   strength     = 5
       type = militia
	   model = 3 
      } 
    } 
   landunit = 
   {  id       = {  type = 10100 id = 22  } 
     location = 1620 
     name     = "Territoriaal Commando Molukken" 
     Division = 
     {  id   = {  type = 10100 id = 23  } 
       name = "TC Molukken" 
	   strength     = 15
       type = militia
	   model = 3 
      } 
    } 

   navalunit = 
   {  id       = {  type = 10100 id = 24  } 
     location = 1653
     base     = 1653 
     name     = "Oostindies Marine" 
     Division = 
     {  id    = {  type = 10100 id = 25  } 
       name  = "Hr.Ms. De Zeven Provinciën" 
       type  = heavy_cruiser
       model = 1
	extra1 = naval_fire_controll_s
	brigade_model1 = 0
      } 
     Division = 
     {  id    = {  type = 10100 id = 26  } 
       name  = "Hr.Ms. Java" 
       type  = light_cruiser
       model = 2
	extra1 = floatplane
	brigade_model1 = 3
      } 
     Division = 
     {  id    = {  type = 10100 id = 27  } 
       name  = "Hr.Ms. Sumatra" 
       type  = light_cruiser
       model = 2
	extra1 = floatplane
	brigade_model1 = 3
      } 
     Division = 
     {  id    = {  type = 10100 id = 28  } 
       name  = "1e Torpedojager Flottielje" 
       type  = destroyer 
       model = 4
	strength = 80
      } 
     Division = 
     {  id    = {  type = 10100 id = 29  } 
       name  = "3e Torpedoboot Flottielje" 
       type  = destroyer 
       model = 0
	strength = 60
      } 
     Division = 
     {  id    = {  type = 10100 id = 30  } 
       name  = "3e Onderzeeboot Flottielje" 
       type  = submarine
       model = 2
	strength = 80
      } 
     Division = 
     {  id    = {  type = 10100 id = 31  } 
       name  = "4e Onderzeeboot Flottielje" 
       type  = submarine
       model = 2
	strength = 80
      } 
     Division = 
     {  id    = {  type = 10100 id = 32  } 
       name  = "5e Onderzeeboot Flottielje" 
       type  = submarine
       model = 2
	strength = 80
      } 
     Division = 
     {  id   = {  type = 10100 id = 33  } 
       name = "3e Transport Flottielje" 
       type = transport 
	   model = 1 
      } 
     Division = 
     {  id   = {  type = 10100 id = 34  } 
       name = "4e Transport Flottielje" 
       type = transport 
	   model = 1 
      } 
     Division = 
     {  id   = {  type = 10100 id = 35  } 
       name = "5e Transport Flottielje" 
       type = transport 
	   model = 1 
      } 
     Division = 
     {  id   = {  type = 10100 id = 36  } 
       name = "6e Transport Flottielje" 
       type = transport 
	   model = 1 
      } 
    } 

   airunit = 
   {  id       = {  type = 10100 id = 37  } 
     location = 1647 
     base     = 1647
     name     = "LA-KNIL" 
     Division = 
     {  id   = {  type = 10100 id = 38  } 
       name = "2e Luchtvaartregiment" 
	   strength     = 20
       type = interceptor
	   model = 6 
      } 
    } 

    division_development =  
    {  name  = "8e Onderzeeboot Flottielje"  
      type  = submarine  
      model = 3  
	new_model = no
      cost  = 0.1  
      id    = {  type = 10100 id = 39  }  
      date  = {  year = 1933 month = july day = 6  }  
     }  

}
