 
 ############################### 
 # Victory points distribution #
 ############################### 
  
 # United States : 25 
 province = {  id = 1809 points = 5  } # Washington D.C. 
 province = {  id = 1795 points = 2  } # New York 
 province = {  id = 1789 points = 1  } # Boston 
 province = {  id = 1805 points = 1  } # Philadelphia 
 province = {  id = 1845 points = 1  } # Detroit 
 province = {  id = 1832 points = 1  } # Chicago 
 province = {  id = 1953 points = 1  } # Miami 
 province = {  id = 1778 points = 1  } # Guantánamo 
 province = {  id = 1739 points = 1  } # Midway Island 
 province = {  id = 1734 points = 1  } # Pearl Harbour 
 province = {  id = 1931 points = 1  } # New Orleans 
 province = {  id = 1908 points = 1  } # Denver 
 province = {  id = 1924 points = 1  } # Dallas 
 province = {  id = 1928 points = 1  } # Houston 
 province = {  id = 889 points = 1  } # Panamá 
 province = {  id = 2142 points = 1  } # Anchorage 
 province = {  id = 1886 points = 1  } # San Diego 
 province = {  id = 1887 points = 1  } # Los Angeles 
 province = {  id = 1889 points = 1  } # San Francisco 
 province = {  id = 1874 points = 1  } # Seattle 
  
 # Germany : 22
 province = {  id = 163 points = 5  } # Berlin 
 province = {  id = 179 points = 2  } # Munich 
 province = {  id = 177 points = 1  } # Nuremberg 
 province = {  id = 131 points = 1  } # Cologne 
 province = {  id = 154 points = 1  } # Hamburg 
 province = {  id = 145 points = 1  } # Essen 
 province = {  id = 184 points = 1  } # Königsberg !!!
 province = {  id = 173 points = 1  } # Dresden !!!
 province = {  id = 181 points = 1  } # Danzig !!!
 
 # United Kingdom : 18
 province = {  id = 29 points = 5  } # London 
 province = {  id = 348 points = 3  } # Gibraltar 
 province = {  id = 900 points = 3  } # Suez 
 province = {  id = 18 points = 1  } # Sheffield 
 province = {  id = 429 points = 1  } # Malta 
 province = {  id = 11 points = 1  } # Glasgow 
 province = {  id = 1432 points = 1  } # Singapore !!!
 province = {  id = 1593 points = 1  } # Guadalcanal !!!
 province = {  id = 1371 points = 1  } # Hong Kong !!!
 province = {  id = 1511 points = 1  } # Colombo !!!
  
 # USSR : 18 (21 with Baltics)
 province = {  id = 572 points = 5  } # Moscow 
 province = {  id = 553 points = 3  } # Leningrad 
 province = {  id = 663 points = 2  } # Stalingrad 
 province = {  id = 535 points = 1  } # Murmansk 
 province = {  id = 599 points = 1  } # Minsk 
 province = {  id = 617 points = 1  } # Kiev 
 province = {  id = 641 points = 1  } # Sevastopol 
 province = {  id = 1191 points = 1  } # Vladivostok 
 province = {  id = 1138 points = 1  } # Omsk !!!
 province = {  id = 713 points = 1  } # Baku !!!
 province = {  id = 1142 points = 1  } # Novosibirsk !!!
 province = {  id = 1103 points = 1  } # Tashkent !!!
 province = {  id = 1151 points = 1  } # Sverdlosk !!!
 
 province = {  id = 262  points = 1  } #Kaunas 
 province = {  id = 270  points = 1  } #Tallinn 
 province = {  id = 264 points = 1  } # Riga !!!
  
 # Japan : 16
 province = {  id = 1552 points = 5  } # Tokyo 
 province = {  id = 1551 points = 1  } # Akita 
 province = {  id = 1557 points = 1  } # Nagoya 
 province = {  id = 1553 points = 1  } # Osaka 
 province = {  id = 1560 points = 1  } # Fukuoka 
 province = {  id = 1563 points = 1  } # Okinawa 
 province = {  id = 1228 points = 1  } # Seoul 
 province = {  id = 1221 points = 1  } # Pyongyang 
 province = {  id = 1362 points = 1  } # Taiyuan 
 province = {  id = 1661 points = 1  } # Iwo Jima 
 province = {  id = 1667 points = 1  } # Truk !!!
 province = {  id = 1219 points = 1  } # Port Arthur / Dalian !!!

 # France : 13
 province = {  id = 55 points = 4  } # Paris 
 province = {  id = 74 points = 1  } # Vichy 
 province = {  id = 52 points = 1  } # Lille !!!
 province = {  id = 37 points = 1  } # Brest !!!
 province = {  id = 68 points = 1  } # Bordeaux 
 province = {  id = 89 points = 1  } # Marseille 
 province = {  id = 907 points = 1  } # Brazzaville 
 province = {  id = 727 points = 1  } # Algiers 
 province = {  id = 718 points = 1  } # Casablanca !!!
 province = {  id = 747 points = 1  } # Tunis !!!
  
 # China : 12
 province = {  id = 1337 points = 2  } # Nanjing 
 province = {  id = 1299 points = 2  } # Chongqing 
 province = {  id = 1247 points = 1  } # Beiping 
 province = {  id = 1338 points = 1  } # Shanghai 
 province = {  id = 1354 points = 1  } # Ganzhou 
 province = {  id = 1260 points = 1  } # Yan'an 
 province = {  id = 1390 points = 1  } # Kunming 
 province = {  id = 1369 points = 1  } # Guangzhou 
 province = {  id = 1297 points = 1  } # Chengdu
 province = {  id = 1283 points = 1 } # Ge'ermu
 province = {  id = 1317 points = 1 } # Wuhan
 province = {  id = 1308 points = 1 } # Changsha

 # Mengkukuo : 2
 province = {  id = 1246 points = 1  } # Zhangyuan
 province = {  id = 1238 points = 1  } # Huhehaote
 
 # Manchukuo : 2
 province = {  id = 1208 points = 1  } # Changchun
 province = {  id = 1214 points = 1  } # Shenyang
  
 # Italy : 9
 province = {  id = 396 points = 1  } # Genoa !!!
 province = {  id = 407 points = 1  } # Milan 
 province = {  id = 750 points = 1  } # Tripoli 
 province = {  id = 419 points = 2  } # Rome # Raised 1 to 2 !!!
 province = {  id = 421 points = 1  } # Naples 
 province = {  id = 422 points = 1  } # Taranto 
 province = {  id = 430 points = 1  } # Palermo 
 province = {  id = 765 points = 1  } # Tobruk !!!
  
 # India : 7
 province = {  id = 1409 points = 1  } # Mandalay 
 province = {  id = 1415 points = 1  } # Rangoon 
 province = {  id = 1517 points = 1  } # Bombay 
 province = {  id = 1447 points = 1  } # Calcutta 
 province = {  id = 1459 points = 1  } # Delhi 
 province = {  id = 1533 points = 1  } # Karachi !!!
 province = {  id = 1487 points = 1  } # Hyderabad !!!
  
 # Middle East : 5
 province = {  id = 1008 points = 1  } # Tel Aviv !!!
 province = {  id = 1019 points = 1  } # Beirut !!!
 province = {  id = 1016 points = 1  } # Damascus !!!
 province = {  id = 1034 points = 1  } # Baghdad !!!
 province = {  id = 1032 points = 1  } # Basrah !!!
 province = {  id = 1049 points = 1  } # Mecca (very important for Muslim nations) !!!
 province = {  id = 1045 points = 1  } # Riyadh !!!
 province = {  id = 1085 points = 1  } # Tehran !!!
 province = {  id = 1091 points = 1  } # Gameroon !!!

 # Poland : 5
 province = {  id = 235 points = 1  } # Cracow 
 province = {  id = 224 points = 1  } # Lodz 
 province = {  id = 232 points = 2  } # Warsaw 
 province = {  id = 242 points = 1  } # Lwow !!!

 # Spain : 5 
 province = {  id = 460 points = 1  } # Madrid 
 province = {  id = 474 points = 1  } # Seville 
 province = {  id = 440 points = 1  } # Barcelona 
 province = {  id = 464 points = 1  } # Valencia 
 province = {  id = 441 points = 1  } # La Coruna 
  
 # Australia : 4
 province = {  id = 1690 points = 1  } # Perth !!!
 province = {  id = 1697 points = 1  } # Darwin !!!
 province = {  id = 1707 points = 1  } # Canberra !!!
 province = {  id = 1704 points = 1  } # Brisbane !!!
  
 # Canada : 4 
 province = {  id = 2106 points = 1  } # Winnipeg 
 province = {  id = 2119 points = 1  } # Montréal 
 province = {  id = 2108 points = 1  } # Ottawa 
 province = {  id = 2111 points = 1  } # Toronto 

 # Norway : 4 
 province = {  id = 495 points = 1  } # Narvik 
 province = {  id = 483 points = 1  } # Oslo 
 province = {  id = 493 points = 1  } # Trondheim & Bergen 
 province = {  id = 488 points = 1  } 
  
 # Argentina : 3 
 province = {  id = 2050 points = 1  } # Buenos Aires !!!
 province = {  id = 2052 points = 1  } # La Plata !!!
 province = {  id = 2054 points = 1  } # Cordoba !!!

 # Belgium : 3 
 province = {  id = 115 points = 1  } # Antwerp 
 province = {  id = 116 points = 1  } # Brussels 
 province = {  id = 899 points = 1  } # Leopoldville 

 # Brazil : 3 
 province = {  id = 2059 points = 1  } # Sao Paulo !!!
 province = {  id = 2075 points = 1  } # Rio de Janeiro !!!
 province = {  id = 2070 points = 1  } # Natal !!!

 # Finland : 3 
 province = {  id = 525 points = 1  } # Helsinki !!!
 province = {  id = 531 points = 1  } # Viipuri !!!
 province = {  id = 521 points = 1  } # Vaasa !!!

 # Sweden : 3 
 province = {  id = 2159 points = 1  } # Stockholm !!!
 province = {  id = 2152 points = 1  } # Malmö !!!
 province = {  id = 2167 points = 1  } # Kiruna (very important metal reserves) !!!

 # Switzerland : 3 
 province = {  id = 391 points = 1  } # Geneva !!!
 province = {  id = 392 points = 1  } # Bern !!!
 province = {  id = 389 points = 1  } # Zurich !!!

 # Yugoslavia : 3 
 province = {  id = 352 points = 1  } # Zagreb 
 province = {  id = 355 points = 1  } # Sarajevo 
 province = {  id = 338 points = 1  } # Belgrade 

 # Austria : 2
 province = {  id = 195 points = 1  } # Vienna 
 province = {  id = 190 points = 1  } # Salzburg !!!

 # Bulgaria : 2 
 province = {  id = 321 points = 1  } # Sofia  !!!
 province = {  id = 325 points = 1  } # Burgas !!!

 # Czechoslovakia : 2
 province = {  id = 207 points = 1  } # Prague
 province = {  id = 208 points = 1  } # Bratislava !!!

 # Denmark : 2
 province = {  id = 294 points = 1  } # Copenhagen !!!
 province = {  id = 220 points = 1  } # Arhus !!!
 
 # Egypt : 2
 province = {  id = 789 points = 1  } # Alexandria !!!
 province = {  id = 787 points = 1  } # Cairo !!!

 # Greece : 2 
 province = {  id = 377 points = 1  } # Athens 
 province = {  id = 382 points = 1  } # Iraklion 
  
 # Hungary : 2 
 province = {  id = 284 points = 1  } # Budapest !!!
 province = {  id = 278 points = 1  } # Szekes... !!!

 # Indochina : 2
 province = {  id = 1399 points = 1  } # Saigon
 province = {  id = 1395 points = 1  } # Hanoi !!! 

 # Mexico : 2
 province = {  id = 1993 points = 1  } # Mexico city !!!
 province = {  id = 1968 points = 1  } # Vera Cruz !!!

 # Netherlands : 2
 province = { id = 122 points = 1 } # Amsterdam 
 province = { id = 1999 points = 1 } # Paramaribo 
 
 # Dutch East Indies: 4
 province = { id = 1647 points = 1 } # Batavia 
 # province = { id = 1638 points = 1 } # Bengkuku
 # province = { id = 1659 points = 1 } # Manado 
 # province = { id = 1596 points = 1 } # Hollandia !!!

 # Romania : 3
 province = {  id = 291 points = 1  } # Sibiu
 province = {  id = 316 points = 1  } # Bucharest 
 province = {  id = 311 points = 1  } # Ploesti 

 # Turkey : 2 
 province = {  id = 1075 points = 1  } # Ankara 
 province = {  id = 409 points = 1  } # Istanbul

 # Venezuela : 2
 province = {  id = 1974 points = 1  } # Caracas !!!
 province = {  id = 1995 points = 1  } # Maturin !!!

 # Chile : 2
 province = {  id = 2023 points = 1  } # Santiago de Chile !!!
 province = {  id = 2024 points = 1  } # Valparaiso !!!
 
 # Colombia : 2
 province = {  id = 1991 points = 1  } # Bogota !!!
 province = {  id = 1986 points = 1  } # Barranquilla !!!

 # Ethiopia : 1
 province = {  id = 825 points = 1  } # Addis Abeba !!!

 # New Zealand : 2
 province = {  id = 1721 points = 1  } # Wellington !!!
 province = {  id = 1722 points = 1  } # Christchurch !!!

 # Portugal : 1
 province = {  id = 476 points = 1  } # Lissabon !!!
 province = {  id = 481 points = 1  } # Porto !!!

 # Siam : 1
 province = {  id = 1423 points = 1  } # Bangkok !!!
 province = {  id = 1424 points = 1  } # Nakhon Sawan!!!

 # South Africa : 1
 province = {  id = 880 points = 1  } # Cape Town !!!
 province = {  id = 876 points = 1  } # Johannesburg !!!

 # Uruguay : 1
 province = {  id = 2052 points = 1  } # Montevideo !!!

 # Ireland : 2
 province = { id = 34 points = 1 } # Dublin !!!
 province = { id = 31 points = 1 } # Cork !!!
