 country = 
 {  tag                    = ENG 
 ai = "ENG_1936.ai"
landdivision = { dormant = yes id = { type = 12700 id = 10019 }  name = "Allied expeditionary corps"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes } # Narvik
landdivision = { dormant = yes id = { type = 12700 id = 10020 }  name = "5th Infantry Division"  type = infantry model = 9 extra = artillery brigade_model = 9 } # BEF (Lille)
landdivision = { dormant = yes id = { type = 12700 id = 10021 }  name = "1st Infantry Division"  type = infantry model = 9 extra = artillery brigade_model = 9 }
landdivision = { dormant = yes id = { type = 12700 id = 10022 }  name = "2nd Infantry Division"  type = infantry model = 9 extra = armored_car brigade_model = 4 }
landdivision = { dormant = yes id = { type = 12700 id = 10023 }  name = "48th (South Midland) Infantry Division"  type = infantry model = 9 }
landdivision = { dormant = yes id = { type = 12700 id = 10024 }  name = "3rd Infantry Division"  type = infantry model = 9 extra = engineer brigade_model = 4 }
landdivision = { dormant = yes id = { type = 12700 id = 10025 }  name = "4th Infantry Division"  type = infantry model = 9 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes id = { type = 12700 id = 10026 }  name = "150th Infantry Division"  type = infantry model = 9 }
landdivision = { dormant = yes id = { type = 12700 id = 10027 }  name = "42nd Infantry Division"  type = infantry model = 9 }
landdivision = { dormant = yes id = { type = 12700 id = 10028 }  name = "44th Infantry Division"  type = infantry model = 9 }
landdivision = { dormant = yes id = { type = 12700 id = 10029 }  name = "51st (Highland) Infantry Division"  type = infantry model = 9 extra = engineer brigade_model = 4 }
landdivision = { dormant = yes id = { type = 12700 id = 10030 }  name = "12th Infantry Division"  type = infantry model = 9 }
landdivision = { dormant = yes id = { type = 12700 id = 10031 }  name = "23rd (Northumbrian) Infantry Division"  type = infantry model = 9 extra = artillery brigade_model = 9 }
landdivision = { dormant = yes id = { type = 12700 id = 10032 }  name = "46th Infantry Division"  type = infantry model = 9 extra = artillery brigade_model = 9 }
landdivision = { dormant = yes id = { type = 12700 id = 10033 }  name = "1st Armoured Division"  type = armor model = 0 extra = sp_artillery brigade_model = 0 }
landdivision = { dormant = yes id = { type = 12700 id = 10034 }  name = "British 52nd (Lowland) Infantry Division"  type = infantry model = 9 extra = artillery brigade_model = 9 }
landdivision = { dormant = yes id = { type = 12700 id = 10035 }  name = "1st Canadian Infantry Brigade"  type = infantry model = 9 extra = artillery brigade_model = 9 }
landdivision = { dormant = yes id = { type = 12700 id = 10036 }  name = "Corps Troops"  type = hq model = 3 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes id = { type = 12700 id = 10037 }  name = "50th Motor Infantry Division"  type = motorized model = 1 extra = tank_destroyer brigade_model = 0 }
landdivision = { dormant = yes id = { type = 12700 id = 10038 }  name = "Royal Armoured Corps"  type = armor model = 0 extra = sp_artillery brigade_model = 0 }
landdivision = { dormant = yes id = { type = 12700 id = 10039 }  name = "21st Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes } # Exeter
landdivision = { dormant = yes id = { type = 12700 id = 10040 }  name = "2nd New Zealand Division"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes } # Irakleon
   }
 country = 
 {  tag                    = SOV 
 ai = "SOV_1936.ai"
landdivision = { dormant = yes id = { type = 10848 id = 300 }  name = "1st Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
landdivision = { dormant = yes id = { type = 10848 id = 301 }  name = "2nd Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
landdivision = { dormant = yes id = { type = 10848 id = 302 }  name = "3rd Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
landdivision = { dormant = yes id = { type = 10848 id = 303 }  name = "4th Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
landdivision = { dormant = yes id = { type = 10848 id = 304 }  name = "5th Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
landdivision = { dormant = yes id = { type = 10848 id = 305 }  name = "6th Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
landdivision = { dormant = yes id = { type = 10848 id = 306 }  name = "7th Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
landdivision = { dormant = yes id = { type = 10848 id = 307 }  name = "8th Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
landdivision = { dormant = yes id = { type = 10848 id = 308 }  name = "9th Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
landdivision = { dormant = yes id = { type = 10848 id = 309 }  name = "10th Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
landdivision = { dormant = yes id = { type = 10848 id = 310 }  name = "11st Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
landdivision = { dormant = yes id = { type = 10848 id = 311 }  name = "12nd Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
landdivision = { dormant = yes id = { type = 10848 id = 312 }  name = "13rd Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 } #removed locked function so ai can put free units better to use
landdivision = { dormant = yes id = { type = 10848 id = 313 }  name = "14th Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 } #removed locked function so ai can put free units better to use
landdivision = { dormant = yes id = { type = 10848 id = 314 }  name = "15th Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 } #removed locked function so ai can put free units better to use
landdivision = { dormant = yes id = { type = 10848 id = 315 }  name = "16th Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
landdivision = { dormant = yes id = { type = 10848 id = 316 }  name = "17th Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
landdivision = { dormant = yes id = { type = 10848 id = 317 }  name = "18th Guards Div"  type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
  }

 province = { id = 247 landfort = 3 } # Brest Fortress